### ISSUE TITLE
Have saved query open new editor

### ISSUE THREAD

**Issue by jungle-boogie** [little-brother/sqlite-gui#10]
Hi,

For your consideration...

When an editor is already opened and has text in the editor, running a saved query will put the text in the same open editor. If you run the two different queries, you get two different results tabs, which is neat, but I would rather have a saved query put the text in a new editor.

**Comment by little-brother** [comment]
Is holding Ctrl while adding query too secretive? If not. I'll add it in the next release.

**Comment by jungle-boogie** [comment]
I would think the default would be to always open in a new editor. Maybe a right-click with a prompt to open in a new editor?

**Comment by little-brother** [comment]
Use `Space` to add query in a new tab.
