### ISSUE TITLE
Auto-update SQL code present into external editor (feature request)

### ISSUE THREAD

**Issue by SilvioGrosso** [little-brother/sqlite-gui#100]
Hello @little-brother 

First off, thanks a lot for the 1.7 release which is extremely **powerful** and stable on Windows 10 :smile:

Here is a feature request also useful since the formatting option in the GUIs is very basic (no line numbers; no option to auto-format the SQL code within sqlite-gui etc etc): 
Add an option to open a SQL file with some code to execute. Once this code it is available in the GUI of sqlite-gui make it possible to *automatically update* it when it has been changed (and *saved*) in the external editor.

For instance:
- Write some SQL code into Notepad++ (open source editor);
- Save it as sql file;
- Open this sql file into sqlite-gui in order to execute it;
- Modify the SQL code into Notepad++ and *save* this change;
- After the previous saving sqlite-gui automatically update the code (in order to execute it) or (even better) asks you about this change.

This option is already implemented with DB Browser for SQLite and it works fine on Windows 10.  Here is a short recording (on Windows 10) related to this implementation:

https://user-images.githubusercontent.com/33007383/158587721-b96086b8-faaf-4e3d-8633-50ac90625592.mp4

Here is the message (notification) of DB Browser when you save some SQL code into the external editor (to let you decide what to do):
![immagine](https://user-images.githubusercontent.com/33007383/158584747-455eeec5-329d-4cd7-aad5-ff7f871bd6b3.png)

Best of luck !

**Comment by little-brother** [comment]
> no line numbers
![изображение](https://user-images.githubusercontent.com/20204037/158598775-8ce6b4e0-3b64-42d9-a864-87e5e9134b2a.png)

> no option to auto-format the SQL code 
![изображение](https://user-images.githubusercontent.com/20204037/158598935-926ae8f5-65c5-42c0-89d9-81dc48f5a566.png)

I don't think that implement support of an external editor instead internal is a good idea. Also a tab don't have any relation to a disk-file e.g. `query1.sql` (there is no option to upload the file content into the tab except `Copy/Paste`).
I know that the internal editor is a very basic that is why I'm already thinking about using [Scintilla](https://www.scintilla.org/).

**Comment by little-brother** [comment]
The comment behaviour was changed.
