### ISSUE TITLE
Deleting/inserting text in the editor takes time proportional to the editor content

### ISSUE THREAD

**Issue by drdcd** [little-brother/sqlite-gui#101]
There is a strange correlation between the time needed to delete (and insert, FWIW, but that is less important) text in the editor and the size of the text already present there. With 8-9 lines, it already takes to long - and there are display artifacts (multiple cursors etc.) left behind. Somethings with the editor repainting looks wrong.

**Comment by little-brother** [comment]
Without any details I can't reproduce the bug.

If you are using x64-version, try to add `msftedit.dll` to the app folder. It's a Richedit component that using for editors. Windows 10 has buggish version of it. That is why x32 version already has it in a distributive.
[msftedit.zip](https://github.com/little-brother/sqlite-gui/files/8409492/msftedit.zip)
 
Feel free to open the issue to provide details.

**Comment by ddumitriu** [comment]
Windows 10 x64, sqlite-x64. With the provided x64\msftedit.dll the symptoms are milder (no parallel cursors etc.) but it is still sluggish.

The editor text is not relevant, this happens with any text. If really needed I can try to post some screen recordings. 

Do I get it right that it is not reproducible for you under w10/64 with sqlite-gui/64?

**Comment by little-brother** [comment]
Yes. I tested the app on Win10x64 without any troubles.

> If really needed I can try to post some screen recordings.

It will be helpfull. 

P.S. This issue is a similar to #25

**Comment by ddumitriu** [comment]
Here you are. For the second video you can see the artifacts starting around 0:17.

The same happens on Win 11 (there I haven't tried the new msftedit.dll).

https://user-images.githubusercontent.com/5046866/161746091-dadc3de2-cf2a-4143-89cb-7ca12592d2fc.mp4


https://user-images.githubusercontent.com/5046866/161746092-407a69a5-3ede-4f4e-b56d-e1c96a6c0951.mp4

**Comment by little-brother** [comment]
Can you check x32 version of sqlite-gui?

**Comment by ddumitriu** [comment]
It behaves just like in video #2 (with the local DLL). In both cases one can see in the status bar how the counter for line number and column number gets updated fast "as expected", yet the repainting of the Edit widget lags completely behind.

**Comment by little-brother** [comment]
Could you check the behaviour without highlighting? To turn it off use `.set use-highlight 0` in `>_` Terminal-tab. To turn it on back use `.set use-highlight 1`.

**Comment by ddumitriu** [comment]
The "fix" version behaves the same. And I cannot use the Terminal tab - it is just black and trying to type in gives system bells.

**Comment by little-brother** [comment]
Is the terminal still unavailable with local dll?
Are you try to use [the top editor](https://raw.githubusercontent.com/little-brother/sqlite-gui/master/resources/terminal.webp)?

**Comment by little-brother** [comment]
Thanks. At least I have a research direction now.

**Comment by little-brother** [comment]
Please check these builds
[sqlite-gui-1.7.1-x64-fix-by-occurance.zip](https://github.com/little-brother/sqlite-gui/files/8454222/sqlite-gui-1.7.1-x64-fix-by-occurance.zip)
[sqlite-gui-1.7.1-x64-fix-by-timer.zip](https://github.com/little-brother/sqlite-gui/files/8454223/sqlite-gui-1.7.1-x64-fix-by-timer.zip)
P.S. Since I can't reproduce this issue on my PC, I'm counting on you.

**Comment by jungle-boogie** [comment]
What is the difference between the builds? I'll test it as well.

**Comment by little-brother** [comment]
The differences under the hood (I'm trying to find a problem place).
`by-occurance`: i turned off an occurance highlighting (highlight a text equals to selection).
`by-timer`: all higlighting (common, brackets and occurance) aren't applied immediately. They wait a timer (50ms).
For users both version should be the same.

**Comment by little-brother** [comment]
Any results?

**Comment by drdcd** [comment]
This will have to wait two or three more days, unfortunately.

little-brother ***@***.***> schrieb am Mo., 11. Apr. 2022,
20:20:

**Comment by drdcd** [comment]
As expected, `by-timer` works, since the editor does not eagerly try to highlight immediately after every stroke. That shows us that simple repainting is quite instantaneously but highlighting does take its resources.

**Comment by little-brother** [comment]
Thanks. It's good to know a root of the issue.
Could you try an alpha-version - https://disk.yandex.ru/d/xEt_c7IyxfiZVA ?
There is no timer, but this version contains a fix for highlighting matching brackets under Win10. Maybe it eliminates the insert/delete-issue too.

**Comment by drdcd** [comment]
No, the alpha version does not solve the issue. I think highlighting is just too demanding to fire directly.

It's not about the machine, but about a clean Win11 - the second laptop had been upgraded from Win10. On the other hand, the desktop stayed with Win10 and exhibits the same problem.

**Comment by little-brother** [comment]
I ponder why I can't reproduce this issue on my PC. Only the deleting issue (end of the first video) was reproduced. 
Do you have 4K monitor? It requires 4x draw-calls against FullHD.

**Comment by drdcd** [comment]
No, there are only stock machines - and plain normal monitors, be it external or laptop.

**Comment by little-brother** [comment]
I hope it was fixed :)
