### ISSUE TITLE
format  error 

### ISSUE THREAD

**Issue by trdm** [little-brother/sqlite-gui#103]
![Screenshot_265](https://user-images.githubusercontent.com/1037036/163038041-be290731-f57a-47bd-a91d-379a04b7e229.png)

query:

> SELECT set1.w AS слово 	,set1.wc AS Повторов 	,set1.d AS Сложность 	,set1.cf AS КоэффСложности 	,set1.ws AS ws_bite 	,stat1.data_time AS ПоследнийРаз FROM ( 	SELECT count(stat.word) AS wc 		,stat.word AS w 		,size_idx AS d 		,MAx(wd.size_CF,1) as cf 		,wd.w_size as ws		 	FROM __Statistic AS stat 	LEFT JOIN w_dificlt AS wd ON wd.word = stat.word 	GROUP BY stat.word 	ORDER BY wc DESC 	) AS set1 LEFT OUTER JOIN ( 	SELECT word AS word 		,Max(data_time) AS data_time 	FROM __Statistic 	GROUP BY word 	ORDER BY word DESC 	) AS stat1 ON set1.w = stat1.word ORDER BY set1.d DESC

right format:

![Screenshot_266](https://user-images.githubusercontent.com/1037036/163038370-e5940a1b-6a01-40f6-bf9b-bdd8ecf5d508.png)

Great program!
Thank you!

**Comment by little-brother** [comment]
Yeah. Thanks for the query example. I found 2 bugs in the formatting code by it.
The issue will be fixed in the next release.

**Comment by little-brother** [comment]
Done
