### ISSUE TITLE
Bad formatting of query

### ISSUE THREAD

**Issue by jungle-boogie** [little-brother/sqlite-gui#104]
Hi,

Take this query and run it through `sqlite-gui` to be formatted:

```
select date, avg(temp) from weather2021
where date between '2021-05-01' and '2021-09-30'
and time between '10:00' and '20:00'
and temp < '93'
group by date
```

It will display as this:

```
select date,
       avg(temp) 
  from weather2021 
 where date between '2021-05-01' and '2021-09-30' and time between '10:00' and ' 20:00 '
and temp < ' 93 '
group by date

```

As a result, none of my data will be returned, because it's putting spaces around `93` and `20:00`

Do you think this could be improved to not pad queries with spaces?

Thanks!

**Comment by little-brother** [comment]
> Do you think this could be improved to not pad queries with spaces?

Impossible! :D

It should be fixed, of course. Thanks for the report.

**Comment by little-brother** [comment]
Fixed.
