### ISSUE TITLE
Toggle comment/uncomment

### ISSUE THREAD

**Issue by jungle-boogie** [little-brother/sqlite-gui#105]
Hello,

1. Open `sqlite-gui` and type `test`
2. Select all text
3. Press `ctrl` + `/`
4. Notice the text is commented out: `/*test*/`
5. Select all text
6. Press `ctrl` + `/`
7. Notice the text is double-commented out: `/*/*test*/*/`

I would expect text that is already commented out to be toggled off and to not remain commented out.

**Comment by little-brother** [comment]
You don't need to select a comment. Just put a cursor inside and press `Ctrl + /`.
But I consider to support uncomment a selection.

P.S. The highlighting problem is detected too.

**Comment by jungle-boogie** [comment]
> You don't need to select a comment. Just put a cursor inside and press Ctrl + /.

That makes the comment like this: `--test` and toggling the comment works fine with this.

**Comment by little-brother** [comment]
Now `/* smt */` can be uncomment as usual via selection plus `Ctrl + /`.
