### ISSUE TITLE
Chart improvements

### ISSUE THREAD

**Issue by jungle-boogie** [little-brother/sqlite-gui#106]
Hello,

Please see the attached chart and notice the values are cut off on the left margin.

Also, the X margin is the date. Would it be possible to have more points than every 10 days?

![image](https://user-images.githubusercontent.com/1111743/167211609-0327312d-da55-494b-a7a1-c620698180a3.png)

Thanks!

**Comment by jungle-boogie** [comment]
Actually both margins have the values cut off.

**Comment by jungle-boogie** [comment]
Also, when selecting bars, `sqlite-gui` crashes.

**Comment by little-brother** [comment]
> the values are cut off on the left margin.

Right values are cuttet too. I'll check how DB4S works with the long values.

> Would it be possible to have more points than every 10 days?

The grid with each day will be dirty. The grid draws 4-5 lines depending on data. Maybe I should pay attention to a window size (a big window can have more lines).

> Also, when selecting bars, sqlite-gui crashes.

Could ypu provide a data example? (You can store a some result as csv and attach it here).

**Comment by jungle-boogie** [comment]
What's up with the second from top horizontal line?

**Comment by jungle-boogie** [comment]
[LasVegasWeatherData.zip](https://github.com/little-brother/sqlite-gui/files/8643820/LasVegasWeatherData.zip)


See attached database

**Comment by little-brother** [comment]
> What's up with the second from top horizontal line?

That's how algorithm works. It inteded to draw lines with most whole values.

> See attached database

Could you provide the problematic `select`-statement. I queried all data and `bars`-chart works.

**Comment by jungle-boogie** [comment]
Try this

Select date, avg(temp) as avg_temp from weather2021
Where date between(‘2021-05-01’) and (‘2022-05-31’)

**Comment by jungle-boogie** [comment]
Updated the query. I forgot to group by the date.

**Comment by little-brother** [comment]
Ok, I reproduced the error. The issue is a trivial: bars requieres at least one text-column to `group by `-selector. The query doesn't have one.

**Comment by little-brother** [comment]
Grid line counts depend on window size. 
You can adjust the grid size by changing `chart-grid-size-x` (100) and `chart-grid-size-y` (50) in a terminal.
