### ISSUE TITLE
Tab stop for find/replace dialog box

### ISSUE THREAD

**Issue by jungle-boogie** [little-brother/sqlite-gui#107]
Hello,

When using tab with the find/replace dialog box, it skips over the blank fields for find and replace, and only tab stops for find, replace, replace all.

Would you please consider adding tab stops to the blank fields?

Thanks!

**Comment by little-brother** [comment]
Ha, I thought that `TAB`-stop is supported by default. I was wrong :( I'll fixed it.

**Comment by little-brother** [comment]
Done.
