### ISSUE TITLE
New tab shortcut?

### ISSUE THREAD

**Issue by jungle-boogie** [little-brother/sqlite-gui#108]
Hi,

I thought there was a shortcut for new tabs, but I can't seem to find it.

Am I looking in the wrong place?

If there is no shortcut for a new tab, could you consider adding it?

![image](https://user-images.githubusercontent.com/1111743/168318486-4804ffbb-4a81-4ef6-ba1c-bffcffe14d45.png)

Thanks!

**Comment by little-brother** [comment]
![изображение](https://user-images.githubusercontent.com/20204037/168343012-1ecc5c9b-381f-4cd7-a132-6133be7eb8eb.png)
?

**Comment by jungle-boogie** [comment]
Ah, that's under *global*. My mistake!
