### ISSUE TITLE
Editor - find next text occurrence

### ISSUE THREAD

**Issue by jungle-boogie** [little-brother/sqlite-gui#109]
Hi,

Take this query:

```
select b.price,
       b.author,
       b.title,
       sum(ob.quantity) cnt 
  from order_books ob 
  inner join books b on ob.book_id = b.id 
 group by book_id 
 order by  3 desc 
 limit 5;
```

Highlight `select` and notice it will skip down and highlight `author`.

In fact, `author` will be highlighted multiple times for various 'find next occurrence`.

I think it may be because there are no multiple occurrence of phrases, so it defaults to `author`.

Thanks!

**Comment by little-brother** [comment]
Could you porvide a screenshot?

**Comment by jungle-boogie** [comment]
hmmm, now I don't see the same behavior, but the F3 button for find next occurrence also doesn't work.

```
select b.price,
       b.author,
       b.title,
       sum(ob.quantity) cnt 
  from order_books ob 
  inner join books b on ob.book_id = b.id 
 group by book_id, b.author
 order by  3 desc 
 limit 5;
```

Notice there are two `b.author`.

1. Highlight the first
2. Press F3
3. Notice nothing happens

**Comment by little-brother** [comment]
Occurance highlghting works only for `a-Z0-9`-range to prevent processing for common selection. 
`b.author` contains `.` and therefore occurances aren't highlighted.

**Comment by little-brother** [comment]
The error doesn't reproduced.
