### ISSUE TITLE
Commented out query still executed

### ISSUE THREAD

**Issue by jungle-boogie** [little-brother/sqlite-gui#110]
Hi,

Take this query and run in:

```
select  json_group_array(json_object('id', id, 'title', title, 'price', price)) from books;

select id, title, price from books;

/*select * from books*/
```

Notice there are three tabs opened; 1 for the first query; 1 for the second query, and one for the commented out line.

Why would the commented out line have been executed?

Thanks!

**Comment by little-brother** [comment]
`select 123; ;select 321;` presents 3 queries. The second is an empty query.

But ok, I'll try to exclude empty queries from execution.

**Comment by jungle-boogie** [comment]
I get two results tabs:

![image](https://user-images.githubusercontent.com/1111743/168344564-bf45651e-6088-496c-b027-400cfabf7d3f.png)

But if I add --comment, I'll get three, with the third being the error.

**Comment by little-brother** [comment]
Yeah, `select 123; /*abc*/;select 321;` is a correct example.
I already skip full empty queries. Now it's time for only-comments.

**Comment by little-brother** [comment]
Done.
