### ISSUE TITLE
Crash on copy when transposing json results

### ISSUE THREAD

**Issue by jungle-boogie** [little-brother/sqlite-gui#111]
Hi,

1. Execute this query on the bookstore database:

```
select id, json_group_array(json_object('id', id, 'customer_id', customer_id, 'sale_date', sale_date)) books
from orders 
group by sale_date;
```

2. Transpose the results
3. Copy the books record and notice `sqlite-gui` will crash.

Thanks!

**Comment by jungle-boogie** [comment]
Taking that same query and formatting it, will make it one line:

```
select id, json_group_array(json_object('id', id, 'customer_id', customer_id, 'sale_date', sale_date) ) books from orders group by sale_date;
 ```

**Comment by little-brother** [comment]
> sqlite-gui will crash.

The problem is insufficient memory allocation: `csv`-format (used to copy row) adds addidional quote for `"` e.g. `"aaa"` should be placed to buffer as `""aaa""`. I missed it.

> formatting it, will make it one line

:( Ok. I'll try to fix it.

**Comment by little-brother** [comment]
All fixed.
