### ISSUE TITLE
Syntax highlighting changes with replace all

### ISSUE THREAD

**Issue by jungle-boogie** [little-brother/sqlite-gui#112]
Hi,

1. Take this query:
```
select b.author, b.title, printf("%.2f", avg(r.rating)) rating, count(1) review_count
from reviews r inner join books b on r.book_id == b.id
group by r.book_id, b.author
order by 4 desc, 3 desc
limit 5;
```

2. Make sure you're on line 1
3. Press `ctrl`+`f`
4. Find `b.author` replace all with `c.author`
5. Notice the formatting is now all blue:

![image](https://user-images.githubusercontent.com/1111743/168345292-05561096-477b-45e7-883a-252bed15498d.png)

If you go to the end of the query and do find/replace all, the text color doesn't change.

**Comment by little-brother** [comment]
Fixed.
