### ISSUE TITLE
Formatting breaks query with ==

### ISSUE THREAD

**Issue by jungle-boogie** [little-brother/sqlite-gui#113]
Hi,

Notice this query has two `=` symbols:
```
select b.author, b.title, printf("%.2f", avg(r.rating)) rating, count(1) review_count
from reviews r inner join books b on r.book_id == b.id
group by r.book_id
order by 4 desc, 3 desc
limit 5;
```

Run it through the formatting, then execute query.

Notice the query is now broken:
```
inner join books b on r.book_id = = b.id 
```

Thanks!

**Comment by little-brother** [comment]
`==` is a not a valid construction.

**Comment by jungle-boogie** [comment]
Ah, I see.

I'm using the bookstore database and a view had `==`. 

The `v_popular5` view.
