### ISSUE TITLE
Matching words not highlighted when no space follows

### ISSUE THREAD

**Issue by jungle-boogie** [little-brother/sqlite-gui#114]
Similar to https://github.com/little-brother/sqlite-gui/issues/109

1. Take this and put into a new editor:
`foo bar biz baz foo bar biz baz foo`

2. Double-click on the first `foo` and notice the last foo is not highlighted.
3. Go to the last `foo` and add a space
4. Go to the first `foo` and double-click all the values up and down the list

Because the last `foo` did not have a space after it, it was not highlighted.

I would expect matching words to be highlighted.

Thanks!

**Comment by little-brother** [comment]
It's a bug.

**Comment by little-brother** [comment]
Done.
