### ISSUE TITLE
Constant crashing with 1.7.3

### ISSUE THREAD

**Issue by jungle-boogie** [little-brother/sqlite-gui#117]
Hello,

With `sqlite-gui 1.7.3`, I am experiencing constant crashing when switching between editor tabs with my database.

I don't know if it's my database, my prefs.sqlite file, my SQL queries, but it's annoying, frustrating, and unexpected.

I'll switch to 1.7.2 to see if it happens left often there.

Thanks!

**Comment by little-brother** [comment]
Do you mean main top tabs or secondary result tabs?
Please, let me know: 1.7.2 have the similar crushes or not.

**Comment by jungle-boogie** [comment]
The editor tabs are what I'm talking about.

> P.S. I suspect changes relating to query highlighting.

Yeah, I think it's related to that. Seems to crash most often when I'm highlighting text from one editor tab to paste into another editor tab.

**Comment by little-brother** [comment]
The highligting is called when you switch between editor tabs too.

**Comment by jungle-boogie** [comment]
Version 1.7.2 is much more stable. I don't exactly know what part of highlighting causes the crashing in the later version.

**Comment by little-brother** [comment]
I have reproduce the issue on Win10. Simple `Paste` and undo by `Ctrl + Z` 
```
{% for row in query("select * from books limit ?1", 3) %} select {{ quote(row.author) }}; {% endfor %}
{% for row in query("select * from books limit ?1", 3) %} select {{ quote(row.author) }}; {% endfor %}
```
will crash the app. It's a good start point to debug.

P.S. I forgot there were many refactoring changes with editors. Perhaps, highlighting is not to blame.

**Comment by little-brother** [comment]
Please check - [sqlite-gui.1.7.3-x64-fix.zip](https://github.com/little-brother/sqlite-gui/files/8900929/sqlite-gui.1.7.3-x64-fix.zip)

**Comment by little-brother** [comment]
I hope it fixed.

**Comment by jungle-boogie** [comment]
Thanks for releasing 1.7.4. I'll use that version for the next several days and see if things are better. I was on vacation with you made the patch, so I couldn't test it.
