### ISSUE TITLE
Home/End keys don't work with drop down column list

### ISSUE THREAD

**Issue by jungle-boogie** [little-brother/sqlite-gui#121]
Hi,

When you're typing a query out, `sqlite-gui` will auto complete the column names, but you cannot use the home, end, page up, page down keys to scroll through the list.

![image](https://user-images.githubusercontent.com/1111743/179320916-9bb13792-43cd-4991-9f43-e92b64d3bac6.png)

If I want available, I can type an `a` or arrow down.

I would like home/end keys to work in this drop down list.

Thanks!

**Comment by wdscxsj** [comment]
Agreed. And can we use **Tab-completion** in addition to Enter-completion?

Another suggestion is an **option to turn off the auto-completion**. This will help (or force) novices to memorize the correct SQL syntax, rather than rely on tools too quickly.

**Comment by little-brother** [comment]
Done.

**Comment by wdscxsj** [comment]
The Tab-completion in v1.7.7 is quite nice. And the option to turn off auto-completion... Maybe the next release? :smile:

**Comment by little-brother** [comment]
Since 1.7.7 you can turn off the autocomplete in the terminal by `.set use-autocomplete 0`.

**Comment by wdscxsj** [comment]
Thanks!
