### ISSUE TITLE
Database diagram - allow to reset view

### ISSUE THREAD

**Issue by blahetal** [little-brother/sqlite-gui#122]
Hello
Would you consider adding a button to "Database diagram" window to reset view of the diagrams? I moved one of the rectangles/tables outside of the Database diagram window and now I cannot move it back (I can only resize it). Resetting the view would move all the rectangles/tables to their default positions like when the window was open for the first time.

Regards
Libor

**Comment by little-brother** [comment]
You can move all tables. Just hold mouse on empty place and drag.

https://user-images.githubusercontent.com/20204037/181112867-f1404760-5e0e-4b90-bf40-b0b07dfb80b7.mp4

**Comment by blahetal** [comment]
How could I miss it, thanks.
