### ISSUE TITLE
Editor font not configurable

### ISSUE THREAD

**Issue by wdscxsj** [little-brother/sqlite-gui#123]
Thank you for this slick tool, but on my machine (Windows 10 Simplified Chinese Edition) the font configuration only affects the database list, but not the editor. For example, a sans-serif font is used for the editor when "Consolas 10" is specified.

![Screenshot183](https://user-images.githubusercontent.com/863369/181667767-d9959781-341a-45b1-8046-87ddb2fc6b89.png)

Update: The font for the editor of Query — Shortcuts dialog is OK. And it properly maintains the keyboard focus after switching away and back, as reported in #124.

![Screenshot184](https://user-images.githubusercontent.com/863369/181675901-3183e828-0817-43af-b69e-c3463e36ba23.png)

**Comment by little-brother** [comment]
1. What is happening with a resultset font? Is it changed? 
2. Please check x32 version. Did this version has the same issue? (x32 version uses a Win7 editor dll).

**Comment by wdscxsj** [comment]
Thanks for your reply! The resultset font is properly changed. And indeed, the 32-bit version works all OK.

**Comment by little-brother** [comment]
Try to put this [msftedit.zip](https://github.com/little-brother/sqlite-gui/files/9219524/msftedit.zip) (Win7x64-version) into sqlite-gui folder and restart the app. Is the issue gone?

I suspect the issue can be related with an editor control library (msftedit).

**Comment by wdscxsj** [comment]
Yes, the extra DLL fixes this issue. Thank you very much!

**Comment by little-brother** [comment]
I didn't reproduce the error on my PC with Win10 and therefore I can fix it.
It's definitely a problem. I'll mention it in Wiki later.

Thanks for report!
