### ISSUE TITLE
Focus lost after switching away and back

### ISSUE THREAD

**Issue by wdscxsj** [little-brother/sqlite-gui#124]
Steps to reproduce:

1. Put keyboard focus on the editor.
2. Switch to another program.
3. Switch back to sqlite-gui.
4. The focus is lost: cannot continue entering text in the editor unless the focus is manually set.

**Comment by little-brother** [comment]
Done.

**Comment by wdscxsj** [comment]
Thanks for your wonderful work! But there is still a minor issue in v1.7.6. If Alt+Tab is used to switch away and back, the editor is so sensitive that an extra Tab character is often entered, unless the key combination is released really quickly. Other editors don't have this issue.

By the way, I find msftedit.dll is not included in the x64 releases of v1.7.6. Without it the editor font is still incorrect.

**Comment by little-brother** [comment]
> Tab character is often entered

It should be considered as a bug.

> I find msftedit.dll is not included

If other issues are found, then I'll include `msftedit.dll` to x64-distributive.

**Comment by little-brother** [comment]
Fixed.
