### ISSUE TITLE
Crash with undo (after formatting: ctr+t shortcut)

### ISSUE THREAD

**Issue by SilvioGrosso** [little-brother/sqlite-gui#125]
Hello @little-brother 

Tested on:
*Windows 10  and Windows 8.1 (64 bit)*
With:
*sqlite-gui.1.7.6-x64-no-ciphers*

These past days, I have been testing sqlite-gui and I got frequent crash when undoing (ctr+z):

Unfortunately, they are *very* difficult to reproduce and sometimes they do not occur at all while undoing.

After many trials and errors, I have got at least one way to always reproduce the crash :-)

It suffices to:
- launch sqlite-gui
- format your SQL code (ctr+t) 
- undo this change (ctr+z):
- *sqlite-gui.1.7.6-x64-no-ciphers* always crahes here.

Here is a screenshot of the crash with Windows 8.1 (the same occurs on Windows 10  64 bit):
![immagine](https://user-images.githubusercontent.com/33007383/182926113-aa5a1904-0e0e-4770-81cc-9fecf29ad72b.png)

**Comment by little-brother** [comment]
Thanks. I'll check it.
