### ISSUE TITLE
Crash on copy-pasting SQL code between 2 windows editor

### ISSUE THREAD

**Issue by SilvioGrosso** [little-brother/sqlite-gui#127]
Hello @little-brother 

**Windows 10 (64 bit)
sqlite-gui.1.7.6-x64-no-ciphers**

There is a crash which is very easy to always reproduce.
It suffices to:
- create a new database or work on an existing one;
- copy big amount of SQL code (no matter what!)  from the window editor;
-  add (+) another editor window and paste this code;
- click on the first window editor (the one in which you have copied the SQL code)
- sqlite-gui always crashes here.

Here is the code I copy-pasted between 2 windows (but the crash occurs with any sql code...):
create table regionali
(id integer primary key not null,
name text not null,
surname text not null,
age integer,
birth text, 
salary real,
job text default 'agronomist',
hired text,
check (birth < '1998-01-01'))
strict;

Here is a video with all my steps to reproduce this crash:

https://user-images.githubusercontent.com/33007383/183462983-8126ae67-f5f5-4aac-acb2-583ca6aa558d.mp4

This being noted, I am really enjoying working with sqlite-gui. 
It is extremely powerful indeed :-)
Thanks for releasing it!

**Comment by little-brother** [comment]
Thanks for the report. I'll check it.

**Comment by SilvioGrosso** [comment]
EDIT:
Actually, this crash does not occur with a new downloaded version of: sqlite-gui.1.7.6-x64-no-ciphers
it only occurs with a version currently used on my computer.
Very strange because all the other options work fine...

**Comment by little-brother** [comment]
Strange. The 1.7.6 version has not changed since release.

**Comment by SilvioGrosso** [comment]
Yep. Strange indeed.
But I get other crashes very easy to reproduce (e.g with undo: CTR+Z) and they are ALL solved as soon as I start working with a fresh install of the 1.7.6.
If you take a look at my video the version "corrupted" is 1.7.6
Same computer of course :-)

**Comment by SilvioGrosso** [comment]
Nope. Actually, I have just closed an editor window (there were 3 opened) and even this fresh install crashed :-)
It is much more stable but  there might be some problem somewhere :-)

**Comment by little-brother** [comment]
Perhaps, it's a problem with `msftedit.dll` library under Win10.
Please try to unpack [msftedit.zip](https://github.com/little-brother/sqlite-gui/files/9375425/msftedit.zip) from Win7x64 to the app folder. This should solve #125 too.

**Comment by SilvioGrosso** [comment]
Hello @little-brother 

> Perhaps, it's a problem with msftedit.dll library under Win10.

You are a *genius* :-)
It does work: no crash whatsoever. It even seems to resolve 125 too.

BTW, on *ALL* versions I have tested so far (Windows 10) there is a lot of flickering when selection big amount of SQL code.
Other applications work fine with the same SQL code (e.g. notepad or notepad++)
Just tested again with this new .ddl 
See this video where I compare notepad with version 1.7.6:


https://user-images.githubusercontent.com/33007383/185445927-96f0b38c-4b61-4ced-8c39-28da20808109.mp4

If necessary, I can open a new ticket :-)
It is not a big bug. However, it is a bit annoying

**Comment by little-brother** [comment]
> If necessary, I can open a new ticket :-)
As you wish, The individual ticket is more convenient for tracking.
P.S. I reproduced the error and I'll try to fix it.
