### ISSUE TITLE
Flickering when selecting big amount of SQL code

### ISSUE THREAD

**Issue by SilvioGrosso** [little-brother/sqlite-gui#129]
Hello @little-brother 

So far, on **Windows 10 (64 bit)**, with all versions I have tested in the past, I have always encountered a little bug.
In short, when I select some part of my SQL code AND I move the cursor's mouse a flickering appears on the window.
This is especially visible with big chunks of code and some part of this code selected.
This only occurs with Sqlite-gui. 
The same code does not create any problem when selected with other application. E.g. Notepad or Notepad++

Tested today with version:
**sqlite-gui.1.7.6-x64-no-ciphers**

See this short video (Windows 10 - 64 bit):

https://user-images.githubusercontent.com/33007383/185473342-e7fd8a23-1f26-473b-a8e1-ddd14abe8705.mp4

**Comment by little-brother** [comment]
Fixed.
