### ISSUE TITLE
Format queries in editor

### ISSUE THREAD

**Issue by jungle-boogie** [little-brother/sqlite-gui#13]
Hi,

Sometimes we can be a little sloppy when writing out a query.

It would be neat if `sqlite-gui` could format queries, so that when we save them, they're saved formatted already.

Thanks!

**Comment by little-brother** [comment]
I have already planned this for implementation. But there are some difficulties for me, even in a simplified version.
So, this feature will not appear soon :(

**Comment by jungle-boogie** [comment]
Understood. I image this would be difficult. What if you were to add syntax highlighting for the time being? That may help people read queries easier.
