### ISSUE TITLE
REST API with curl

### ISSUE THREAD

**Issue by abeq** [little-brother/sqlite-gui#134]
Hi, I have tried REST API but error has occurred:
```
C:\Users\foobar> curl http://127.0.0.1/api/books -X GET
curl: (1) Unsupported HTTP version in response
```
- curl 7.83.1 (Windows)
- curl 7.86.0 (x86_64-w64-mingw32)

Please advise me.

**Comment by little-brother** [comment]
You forgot to specify a port. Your request uses default `80` but `sqlite-gui` waits on `3000`.

**Comment by abeq** [comment]
I thought you are right, but I have tried ```curl http://127.0.0.1:3000/api/books -X GET``` then return same error.
With Chrome, I got expected return.

**Comment by abeq** [comment]
withdrawn

**Comment by little-brother** [comment]
Why? The issue exists. I don't the cause yet.
Sorry, I don't have a time to investifate and fix it immediately.

**Comment by little-brother** [comment]
It was a bug. I forgot to set a response status.
Fixed.
