### ISSUE TITLE
No Way to open temp-file '' (ie, empty filename) or :memory: database

### ISSUE THREAD

**Issue by kmedcalf** [little-brother/sqlite-gui#139]
There is no way to open (or attach) a tempfile (filename is empty string) or :memory: (filename is the magical name :memory:) database.  Can an option be added to allow a "database name specified as a string without a gui selection box" be added?

That is, an "open database" that simply accepts and passes any string (including an empty one) and an "attach" that does the same thing?

**Comment by little-brother** [comment]
You can open an in-memory database by "New/Open" holding Ctrl (you can find it in `Main Menu` > `?` > `Tips`).
I think the same way to attach an in-memory database will be OK.

**Comment by kmedcalf** [comment]
It is shift and it only works for open.  What if I want to open a file using the non-default vfs?  There is no way to enter a name that is not a file in the dialog box.

**Comment by little-brother** [comment]
I have never worked with vfs. I have read [VFS](https://www.sqlite.org/vfs.html)-doc and it looks like it will be easy to add support for other vfs. The main issue is I don't know how to test it properly. There are several demo vfs but only `appendvfs.c` works for me.

**Comment by little-brother** [comment]
Added a special dialog.  Hold `Shift` when choosing `Open` or `Attach`.
