### ISSUE TITLE
Clear terminal view

### ISSUE THREAD

**Issue by jungle-boogie** [little-brother/sqlite-gui#14]
Hi,

I like the terminal view for the results, since it also shows the query.

However, there doesn't seem to be a way to clear the data out. If I open one DB, use the terminal to execute some queries, then close and open another database, the old data is still present in the terminal.

I would request a way to clear the screen/buffer in the terminal view.

Thanks!

**Comment by little-brother** [comment]
I'll add `.clear` and `.history N` commands. Thanks for suggestion.

**Comment by little-brother** [comment]
Done. `.last N` instead `.history N`.
