### ISSUE TITLE
follow cursor. selected cell color

### ISSUE THREAD

**Issue by oemakarov** [little-brother/sqlite-gui#143]
- when i use table editor and navigate rows by keyboard i gues window should follow cursor. now when the cursor step down lower then last visible row on window you can't see cursor anymore.
- color of cursor / selected cell is not so visible. selected row has blue background color, but selected cell was only green border, this is not so clear. other background for secected cell would be preferred.

**Comment by little-brother** [comment]
Done. You can set up the color in Settings.
