### ISSUE TITLE
sqlite-gui (1.7.9 version) crashes after inserting a new record

### ISSUE THREAD

**Issue by sergioferrari** [little-brother/sqlite-gui#146]
Hi Little-Brother,
sqlite-gui (1.7.9 version) crashes after inserting a new record in a table using the "Add row" dialog.
After filling the fields, I click on the "Save and New" button and then on the Close button.
At that moment in the window that displays the table appears a black band on the last inserted line.
By clicking on the "Refresh" button the application crashes and, after a few seconds, closes.
The new record is entered in the database.
I downloaded the application from Github and did not compile it personally.
<img width="755" alt="crash_save_and_new" src="https://github.com/little-brother/sqlite-gui/assets/49869701/3ab0c20f-6274-48b7-8b9f-fc45c0e845ec">

**Comment by little-brother** [comment]
Thanks. 

The data storage was changed for a grid. It looks like I missed something :(
I'll try to fix as soon as possible but I don't reproduce the error myself yet.

**Comment by little-brother** [comment]
Please check the update - [sqlite-gui.1.8.0-x64-alpha.zip](https://github.com/little-brother/sqlite-gui/files/11655617/sqlite-gui.1.8.0-x64-alpha.zip)

**Comment by sergioferrari** [comment]
I made some tests of inserting new records (not many) and it seems that the problem is solved.
Thank you for your quick intervention.
