### ISSUE TITLE
Separate assets with extensions

### ISSUE THREAD

**Issue by nalgeon** [little-brother/sqlite-gui#147]
You've created some great custom extensions (odbc, ora etc). I'd be happy to add them to the SQLite [package registry](https://sqlpkg.org/). But for this to work, the extensions should be distributed as a separate flat archive. For example:

```
extensions-x64.zip
├── exec.dll
├── odbc.dll
├── ora.dll
└── xml.dll

extensions-x86.zip
├── exec.dll
├── odbc.dll
├── ora.dll
└── xml.dll
```

Can you publish them as part of your release process?

**Comment by little-brother** [comment]
Hmmm, I'm not sure that these extensions should be regestered without changes (maybe except xml).
`odbc` and `exec` can be run only on Windows. So they need *nix support.
`ora` contains mostly random function set e.g. `levenshtein`-function have to be removed into `lang`-extension like [distlib](https://github.com/schiffma/distlib).

**Comment by nalgeon** [comment]
I think it's perfectly fine to have Windows-only extensions in the registry. There are a lot of Windows users, why not let them benefit from your extensions. But that's entirely up to you, of course.

**Comment by little-brother** [comment]
Check https://github.com/little-brother/sqlite-extensions
I have created my own extension repository because I need a some repository with binaries and help files to install extensions in the app by one click

![изображение](https://github.com/little-brother/sqlite-gui/assets/20204037/2cb9c18f-9e81-4efb-9a46-daf22be11e0a)

**Comment by nalgeon** [comment]
Thank you! I've added your extensions to the registry.
