### ISSUE TITLE
Automatically check foreign keys or enable via checkbox

### ISSUE THREAD

**Issue by mpjanus** [little-brother/sqlite-gui#148]
By default, foreign keys are not checked / enforced (although you can check for it via the tools).  Via the settings -> extra tab, you can enable this by sending PRAGMA foreign_keys = ON;  and reopen te connection. But this is such important functionality, that I think it should be enabled by default and made available as a checkbox item.

BTW, I love this tool (simple &lightweight), keep up the good work!

**Comment by little-brother** [comment]
Ok. It will be added in the next version simultaneously with the new SQLite release.

**Comment by little-brother** [comment]
Added.
