### ISSUE TITLE
Saved queries can't be deleted

### ISSUE THREAD

**Issue by jungle-boogie** [little-brother/sqlite-gui#15]
Hi,

I like the saved query feature. If I'm working on something complex, I would want to save it often to make sure I don't lose my work. 

However, it doesn't seem like I can delete a query within the GUI, with something like a right-click, or shift right-click.

The saved queries can probably be deleted directly in the `prefs.sqlite`, but it would be nice to see a GUI option for deletion.

Thanks!

**Comment by little-brother** [comment]
Use `Del`. I'm going to add right-button menu later.

**Comment by jungle-boogie** [comment]
Yes! `Del` does work! Sorry that I didn't try that out.

**Comment by little-brother** [comment]
Added a right button menu with all shortcuts.
