### ISSUE TITLE
Add drop-down list with foreign keys in the GUIs (Feature request)

### ISSUE THREAD

**Issue by SilvioGrosso** [little-brother/sqlite-gui#153]
Hello @little-brother 

With many softwares (Db Browser for SQLite, Sqlitestudio, Dbeaver, LibreOffice Calc) whenever you have a foreign key there appears by default, in the GUIs, a drop-down list with all the items you are allowed to select. 
It is quite useful whenever there are plenty of them, therefore you can't remember all of them by heart.

For instance, suppose we create 2 tables:

create table articles(
id integer not null,
fruit text primary key
);

insert into articles (id, fruit) values
(1, 'apple'),
(2, 'kiwi'),
(3, 'pear');

create table buyers (
id integer primary key,
buyer text,
fruit text,
price integer,
FOREIGN KEY (fruit)
REFERENCES articles(fruit)
);

insert into buyers (id, buyer, fruit, price) values
(1, 'Silvio', 'apple', 1500),
(2, 'Marco', 'pear', 1600),
(3, 'Stefano', 'kiwi', 1800);

Now, I want to insert, through the GUIs, a new line (4°) in the table buyers. 
The items (fruit) allowed are: apple - pear - kiwi

Here is what occurs with Db Browser for SQLite:

![image](https://github.com/little-brother/sqlite-gui/assets/33007383/abb95dcf-926a-4cb2-828d-8dcf404781b3)

I suppose it would be quite difficult to add (code) an option to get a drop-down like this in sqlite-gui
This when: **pragma foreign-keys = ON** (in the settings)

However, I am wondering whether it would be possible to add an option with such a list in here (*edit value window*)?

![image](https://github.com/little-brother/sqlite-gui/assets/33007383/efe8368c-a908-46a3-9707-c9dc50caf691)

**Comment by little-brother** [comment]
Could you check "Add row"-dialog in [sqlite-x](https://github.com/little-brother/sqlite-x/releases) (use `Ctrl + Space` to show dropdown list) ? Is it what you asked for?

**Comment by SilvioGrosso** [comment]
Hello @little-brother 

In all truth, I recall having this feature in some old versions of sqlite-gui. 
To make it short, I didn't remember the shortcut to trigger it and **where** it was supposed to work

However, now, I have tried but it does not work (ctr+space) with cursor in fruit
![image](https://github.com/little-brother/sqlite-gui/assets/33007383/2cc0ab29-77ca-45cf-bad4-cfeb6eb57827)

**Comment by little-brother** [comment]
sqlite-gui doesn't have it. Check `sqlite-x`. It's another my small project for SQLite where I test some features  (cause its code is much simpler).

**Comment by SilvioGrosso** [comment]
Yep. it works fine on sqlite-x. 
The drop-down list appears like in the other softwares.

I have noticed it is also possible to hide and move columns, within a table, in the GUIs, which is quite neat.
Not to mention,  the dark theme :smile:

Is this GUIs a QT application?

**Comment by little-brother** [comment]
> Not to mention, the dark theme

sqlite-gui has many forms. So there is a lot of work to colorize them all :(

> Is this GUIs a QT application?

Nope. It uses WinAPI as all another my projects.

**Comment by little-brother** [comment]
Done. Use `Ctrl + Space` to view suggestions.
