### ISSUE TITLE
Add dark theme

### ISSUE THREAD

**Issue by khanaffan** [little-brother/sqlite-gui#154]
This tool seems good so first thanks for writing this. 

For me, this is very bright given everything else is in dark mode. I would suggest either adding a dark theme or allowing setting color for various UI facets.

if I get time I would like to contribute as well.

Thanks
Again.

**Comment by little-brother** [comment]
> This tool seems good so first thanks for writing this.

Thanks.

This request is duplicated to  #119. 
I understand how it's important to have the dark theme and I have already done one attempt with it but without luck. So I reversed the code and postponed it to the next time.
