### ISSUE TITLE
1.9 slow opening 15Mb table

### ISSUE THREAD

**Issue by valsor** [little-brother/sqlite-gui#155]
Thanks for your great work. I was awaiting for the font rendering fix on scaled display and it's here now. Unfortunately some strange behavior occurs when double-clicking on table name in left panel. If table data is relative big (ca 100 000 records, 15MB) it hangs for ca 10-20 seconds with "(Not response)" label added in window title bar. I'm on en-US Windows10 64 bit. I've tried switching off real-time virus protection with no success. Only rolling back to 1.82 solved the problem. Any ideas?

**Comment by little-brother** [comment]
Hmm, there are no changes in `Edit data`-dialog between 1.8.2 and 1.9.0.
Try to replace `sqlite3.dll` by the previous version.
Did you table contain `BLOB`, `json`, generated columns or smth special? 15mb is huge for a typical data.

**Comment by little-brother** [comment]
> Also check in the dialog title how many rows are loaded.  ...

How many rows are loaded in both cases?

**Comment by valsor** [comment]
In dialog title it shows 10000. In settings 10000 too. If I change it to 1000 the table is loaded much faster.

**Comment by valsor** [comment]
1.82 also loads 10000 as in settings.

**Comment by little-brother** [comment]
I managed to repeat this error on Win10x64. I suppose that the issue is related to a common controls library (Windows standard library). 1.9.0 uses 6.0 instead of 4.8 (it allows to use stylized buttons and another input controls) but it also provides that problem :(

Thanks for the report.

**Comment by little-brother** [comment]
Fixed.
