### ISSUE TITLE
[Enhancement] toggle password visibility?

### ISSUE THREAD

**Issue by stokebreakup** [little-brother/sqlite-gui#159]
Hi.

can we toggle password visibility? I.e,

without(toggle password visibility)       |  with(toggle password visibility)
:-------------------------:|:-------------------------:
![image](https://github.com/little-brother/sqlite-gui/assets/165694895/ba8ea08d-7c23-4025-90f7-a01d61501275)  | ![image](https://github.com/little-brother/sqlite-gui/assets/165694895/f9194ed9-2d7c-497e-b414-fc5d1433d909)

?

(I enter a demo password, I do not use any password with this pattern. the data is fictitious. )

thanks again for great app. this is one last question.

regards,

**Comment by little-brother** [comment]
Ok, it will be added in the next release.

**Comment by little-brother** [comment]
Added a special eye-button.
