### ISSUE TITLE
Saved queries date confusing

### ISSUE THREAD

**Issue by jungle-boogie** [little-brother/sqlite-gui#16]
Hi,

I like that you record the datetime with the saved queries, but the format can be confusing to people at first.
It looks like it's DD-MM-YYYY UTC time.

I propose ISO8601 format when recording the date.

YYYY-MM-DDDD UTC time.

https://en.wikipedia.org/wiki/ISO_8601

**Comment by little-brother** [comment]
Perhaps, it should be a configurable setting.

**Comment by jungle-boogie** [comment]
Sure, configurable is fine, but I'd recommend defaulting to ISO8601 as the default.

**Comment by little-brother** [comment]
Date format changed to `YYYY-MM-DD` (without configuration).
