### ISSUE TITLE
Query History record doesn't have spaces on new lines

### ISSUE THREAD

**Issue by jungle-boogie** [little-brother/sqlite-gui#160]
Hello,

FYI...I think this problem has been around as long as there's been a query history table.

1.`sqlite-gui-1.9.0-x64`, write a query where you have a newline:
```
select title from books
where price between 1.0 and 8.0
```
2. Enter query history and notice query is `select title from bookswhere price between 1.0 and 8.0`

I would expect `books where`, since the other spaces appear correctly.

**Comment by little-brother** [comment]
Thanks for the report. It's a standard control problem. I think it will be easy to fix it in the next release.
