### ISSUE TITLE
White stripe covers column name labels in 1.9.1

### ISSUE THREAD

**Issue by valsor** [little-brother/sqlite-gui#163]
Hi there! The new release 1.9.1 eliminates the problem with slowness when opening table in 1.9 but introduces another small visual defect. In opened table window white stripe covers column name labels. See picture. Windows 10 64 with both 100% and 125% scaling.
![sqlite-gui](https://github.com/user-attachments/assets/f2e9d2ed-87f0-4801-8372-387e9620698b)

**Comment by little-brother** [comment]
Thanks for the report.
Definitely I have to test new versions under Win10 :)

**Comment by sergioferrari** [comment]
The filter input line is partially hidden. 
When entering a value and pressing input, the filter line disappears.

**Comment by little-brother** [comment]
The temporary solution is to run any query in an editor and enable `Column filters`.
![изображение](https://github.com/user-attachments/assets/d1d0d357-c51a-4863-ac57-af01982d2a9b)

**Comment by havinhnam** [comment]
In the result table, the all result value can't copy and paste to excel (copy to clipboard value with tsv to paste excel)

**Comment by little-brother** [comment]
Fixed.
