### ISSUE TITLE
Database encryption interface improvement

### ISSUE THREAD

**Issue by Alex-V69** [little-brother/sqlite-gui#165]
Hello. 

I noticed a tiny issue. When I click "OK" of the "Database encryption" window while "Use predefined profile" is not set properly, it just does nothing – it shows no error messages or warnings. It was confusing because I thought at first that encryption capabilities were broken until I brute forced through all possible setting combinations.

Either way, thank you for your work on this amazing project!

**Comment by little-brother** [comment]
Yes, it's a bug. Thanks for the report.

**Comment by little-brother** [comment]
Fixed. Profiles should be used only for legacy-mode.
