### ISSUE TITLE
Database not released from app after close

### ISSUE THREAD

**Issue by jungle-boogie** [little-brother/sqlite-gui#18]
Hi,

In sqlite-gui.1.5.1, if I open a database, work on it, then close it, sqlite-gui.1.5.1 still holds on to the database. As a result, I can't rename the database file.

1. Open sqlite-gui.1.5.1
2. Open a database in sqlite-gui.1.5.1
3. Run simple query so you know DB is open & active
4. Close DB
5. Rename the db file
6. Notice Windows will tell you it's in use

I would expect that the database would be released once the application closes the file.

Thanks!

**Comment by little-brother** [comment]
Thanks. The journal database is toggled to `WAL`-mode. This is a critical bug. I'll try to fix it as soon as possible.

**Comment by jungle-boogie** [comment]
Good point. Simply viewing data causes same issue.

I would expect the database to be released once I close it in the app, though.

**Comment by little-brother** [comment]
Please check this version - https://disk.yandex.ru/d/UoFujQSIAtRNLQ

**Comment by jungle-boogie** [comment]
Yes, that build seems to resolve the issue I noticed.
