### ISSUE TITLE
Put version# somewhere in app

### ISSUE THREAD

**Issue by jungle-boogie** [little-brother/sqlite-gui#19]
Hi,

Please consider adding the version number of your application somewhere.

Typically this is found under the about tab. Maybe it would be nice to also have the SQLite3 version loaded with the app as well.

Thanks!

**Comment by little-brother** [comment]
Check the left corner of the status bar - there are both versions :)

**Comment by jungle-boogie** [comment]
Ah, good job!

**Comment by little-brother** [comment]
![изображение](https://user-images.githubusercontent.com/20204037/147144560-81f3e566-637d-46d8-94cf-b51eed5b0e6d.png)
Coming soon. Now there is more info than before.
