### ISSUE TITLE
Make ctrl+A work in viewer

### ISSUE THREAD

**Issue by jungle-boogie** [little-brother/sqlite-gui#20]
Hi,

I like the data viewer window you have in the app when you double-click on the column name. The where filter is also nice.

Could you please consider having `ctrl+a` work as a highlight all in the where filter and in all the filters below the column names?

`ctrl+A` is a standard behavior in almost anything involving text.

Thanks!

**Comment by jungle-boogie** [comment]
`ctrl`+`A` does not work in the add table window for the name of the table or for the columns in the table.

**Comment by little-brother** [comment]
Done.
