### ISSUE TITLE
Cancel in view doesn't cancel view

### ISSUE THREAD

**Issue by jungle-boogie** [little-brother/sqlite-gui#21]
Hi,

I found an issue when trying to close the edit view window.

1. Open sqlite-gui-1.5.1
2. Open a database with a view
3. Right-click the view
4. Click edit
5. Click cancel
6. Notice the window closes
7. Click Close in the menu bar of sqlite-gui-1.5.51
8. Notice the error message appears:
---------------------------
Info
---------------------------
There are open dialogs. You should close them.
---------------------------
OK   
---------------------------

You cannot close the app, even if you edit the view again and execute the view.
I had to use task manager to kill the app.

I would expect the app cancel button to function properly.

**Comment by jungle-boogie** [comment]
This is even simpler to reproduce than I originally knew.

1. Open sqlite-gui
2. Open a database
3. Right-click on views > Add
4. Press cancel
5. Click close in menu bar.

Notice the message:

```
---------------------------
Info
---------------------------
There are open dialogs. You should close them.
---------------------------
OK   
---------------------------
```

This also seems to happen for indexes and triggers. Only way to close app is to use task manager.

**Comment by little-brother** [comment]
Fixed.
