### ISSUE TITLE
Print line number with error

### ISSUE THREAD

**Issue by jungle-boogie** [little-brother/sqlite-gui#23]
Hi,

To be considered if you implement #22....

When there is an error in the editor, the results pane says there's an error. It could also include the line number with the error.

Thanks!

**Comment by little-brother** [comment]
Done.

**Comment by jungle-boogie** [comment]
Another example:
```
select o.id, o.sale_date, json_group_array(json_object('id', b.id, 'title', b.title, 'price', b.price)) books
from orders o 
inner join order_books ob on o.id = ob.order_id 
inner jon books b on ob.book_id = b.id 
group by o.id;
```

Notice line 4 says `jon`, not `join`

Results tab says:
Error
near "b": syntax error
at line 1

What on line 1 is affecting what I did on line 4?
