### ISSUE TITLE
Terminal view broken when closing tabs at startup

### ISSUE THREAD

**Issue by jungle-boogie** [little-brother/sqlite-gui#24]
Hi,

If you uncheck `Restore editor tabs at startup` (default is checked), the terminal view text is black and you can't read it unless you highlight the text.

1. Open app
2. Database > Settings
3. Uncheck Restore editor tabs at startup
4. Click ok
5. Go to terminal editor and type `.help`
6. Execute
7. Notice you can see text
8. Open a few blank editors
9. Close app
10. Open app
11. Notice extra editor tabs are dismissed (as expected)
12. Go to terminal editor and type `.help`
13. Execute
14. Notice you cannot see the text

I would expect to always see the text.

Thanks!

p.s. you probably want to change at to on:
`Restore editor tabs ON startup`

**Comment by little-brother** [comment]
Fixed.
