### ISSUE TITLE
Editor pane not refreshing fast when updating text

### ISSUE THREAD

**Issue by jungle-boogie** [little-brother/sqlite-gui#25]
Hi,

This may need more experimenting and investigating on your part, because I'm not exactly certain what I'm seeing is related.

It seems saving a query (maybe multiple saves) cause the editor pane to become sluggish and doesn't update to edit/view the query.
The app never crashes or becomes unresponsive, but the editor pane doesn't refresh allowing you to see the text very well.

Thanks!

**Comment by jungle-boogie** [comment]
Here's a video demo of what I'm explaining:

https://user-images.githubusercontent.com/1111743/118381628-8f17dd00-b5a1-11eb-8ff1-cea3f8274426.mp4

I actually didn't have any queries saved, so maybe it's the auto complete that's causing issues?

**Comment by little-brother** [comment]
Could you attach an query text? 
How long does the app work before this behaviour?

**Comment by jungle-boogie** [comment]
I started the recording just seconds after opeining the app.

I would suggest trying to make an elaborate query with the default DB and seeing if you get the same results.

**Comment by little-brother** [comment]
How do you change a words and their cases? I didn't see autocomplete and it doesn't like you input text as usual (maybe fps is not enough). Is it some hotkeys?

**Comment by jungle-boogie** [comment]
Hi,

I select text with shift + arrow keys.

Also test shift + home and end keys.

The video recorded what I saw and experienced. This is not a video playback
issue.

**Comment by little-brother** [comment]
This issue can be related with a long query text and a slow PC. 
Can you run the `Task manager` > `Performance`, edit the query and check CPU usage?

**Comment by jungle-boogie** [comment]
Hi,

My computer may be slower and older than yours, but I have an SSD drive and don't experience any slow issues with any other apps.

**Comment by jungle-boogie** [comment]
Hi,

On a different PC, I see the same results. Highlighting text and replacing it causes the lag with typing.
Task Manager peeked at 18% CPU but only very briefly.

Could this be related to `sqlite-gui` trying to auto complete and it choking on something?

**Comment by little-brother** [comment]
> but I have an SSD drive and don't experience any slow issues with any other apps.

It doesn't matter what kind of drive you are use. Currently the entire text is re-colorized on any change. It requires multiply non-disk API calls to an editor to colorize each word and extremely slow if the text is long enough. The solution is to colorize only the visible  text. I try to implement it.

Please check a version without autocomplete - https://disk.yandex.ru/d/5ASPgXWCkR8E3Q to confirm or deny my version.

**Comment by jungle-boogie** [comment]
Thanks for your analysis. I'll try that version of sqlite-gui out soon.

**Comment by jungle-boogie** [comment]
Hi,

There are some improvements but I still see the problem.

Now all the text appears very quickly after I stop typing, but it doesn't keep up with my typing. 
Once I get it to happen the first time, it seems to always occur, just like before.

**Comment by little-brother** [comment]
Could you provide your OS, the query line count and CPU model?

> Now all the text appears very quickly after I stop typing, but it doesn't keep up with my typing. Sometimes pressing the down arrow key causes the updated text to appear.

Hence, it's a not a highlighting issue and autocomplete is more likely. 
The `down arrow`-key is a very strange. This button doesn't trigger the highlighing update. Maybe a caret is placed to parentheses?

**Comment by jungle-boogie** [comment]
> Could you provide your OS, the query line count and CPU model?

Windows 10 version 1809 OS build 17763.1879 on a Intel core i5-2400 cpu 3.10GHz

The query I'm executing is 14 lines, but it's only using 1 table in my database.

**Comment by little-brother** [comment]
`i5` is more than enough to work without lags. So I need to get Win10 for testing because I use Win7x64 and I can repeat this bug. The `Ctrl + Alt + Esc` also works fine on WinXP/Win7.

**Comment by little-brother** [comment]
I repeated this error in Win10. 
Also I noticed that under Win10 the app is much slower. Perhaps I should change a compiler.

**Comment by jungle-boogie** [comment]
Oh, good to hear you were able to find a machine, and experience the same/similar problem.

**Comment by little-brother** [comment]
It looks like that `msftedit.dll` (is used for editors) in Win10 is a little buggish or internally works different :(
The silly solving is to place [`msftedit.dll`](https://disk.yandex.ru/d/DHbYx47-6bSChA) (32bit) from Windows 7 to sqlite-gui folder.

**Comment by jungle-boogie** [comment]
That DLL does seem to make a difference.

Do you also notice some improvements?

**Comment by little-brother** [comment]
With Win7 dll I couldn't reproduce the paint bug and (possibly) the app works faster.
I think to include this dll to the app distributive.

**Comment by jungle-boogie** [comment]
Yes, seems like app works faster with this DLL.

Glad we got this one taken care of - good job!
