### ISSUE TITLE
Switch editor tab interferes with existing Windows 10 shortcut

### ISSUE THREAD

**Issue by jungle-boogie** [little-brother/sqlite-gui#28]
Hi,

`ctrl`+`alt`+`esc` interferes with an existing Windows shortcut:
https://www.computerhope.com/jargon/a/alt-esc.htm

So pressing this doesn't close the editor tab in the app.

Thanks!

**Comment by little-brother** [comment]
Added alternative: Ctrl + Alt + Backspace
