### ISSUE TITLE
Import schema file and save DB

### ISSUE THREAD

**Issue by jungle-boogie** [little-brother/sqlite-gui#29]
Hi,

You implemented a nice feature in #9 - an in memory database. Thank you for putting that in your tool.

I can create an in memory DB, then import a sql file under Tools > Import SQL File, but I don't see a way where I can save my database after it's been imported.

Would you please consider the ability to convert an in memory DB to disk? That way the DB file can be opened again later.

Thanks!

**Comment by little-brother** [comment]
You can use 
```
vacuum into 'D:/copy.sqlite';
```
I'll think about to add `Save as` menu item.

**Comment by little-brother** [comment]
Added `Database` > `Save as`
