### ISSUE TITLE
Save queries on exit prompt

### ISSUE THREAD

**Issue by jungle-boogie** [little-brother/sqlite-gui#30]
Hi,

If I have a few tabs open and I close the squlite-gui app, there is no prompt to save the queries. (yes/no prompt)

You may want to consider a prompt for the user to save the queries.

Maybe this only needs to be prompted when "Restore editor tabs at startup" is unchecked.

Thanks!

**Comment by little-brother** [comment]
If user choose "Save" when "Restore editor tabs at startup" is unchecked then what are app suppose to do with queries?
Imho, the prompt is annoying. That is why I add "autosave" ability.

**Comment by jungle-boogie** [comment]
If a user has "Restore editor tabs at startup" unchecked, I would expect a "save query?" question for yes/no.

This doesn't mean the query has to be kept in the editor when opening the app back up, though.
Since the default is to have the restore box checked, I don't think this would annoy you.

It's very common for virtually every app to prompt the user to save files when closing.

**Comment by little-brother** [comment]
> the query has to be kept in the editor when opening the app back up, though.
After "yes" queries can be saved to "Saved queries" or extrenal sql file. The first choice is unobvious, the second is out of principle: store all in `prefs.sqlite`.

I don't know for what reason user can turn off auto-save and wants to save queries on exit.

**Comment by jungle-boogie** [comment]
I'll acquiesce to this request. I know that if I uncheck the box, I'll need to save the queries elsewhere.

Thank you.
