### ISSUE TITLE
Wrong line error line number

### ISSUE THREAD

**Issue by jungle-boogie** [little-brother/sqlite-gui#31]
Hi,

Not sure if you saw https://github.com/little-brother/sqlite-gui/issues/23

Regardless of where the error is located, the error text always displays `at line 1`

Thanks!

**Comment by little-brother** [comment]
Thanks. I didn't see.  The best way to notify me is to send me e-mail (lb.im@ya.ru) or create a new issue.

Yes, it's a bug :(

**Comment by jungle-boogie** [comment]
I reported the problem to their project as well. Good find!

**Comment by jungle-boogie** [comment]
I'll resolve this. There doesn't seem to be a decent way to report the line number, since SQLite doesn't report it.

Doing anything clever in `sqlite-gui` would likely be more confusing.
