### ISSUE TITLE
Add button and shortcut to comment/uncomment lines

### ISSUE THREAD

**Issue by jungle-boogie** [little-brother/sqlite-gui#33]
Hi,

Please consider adding a button in the toolbar to comment/uncomment lines in `squlie-gui`.
The user can of course type `--` themselves, but having a button available would be a nice feature to have.

DBBS uses `ctrl`+`/` as a shortcut to comment/uncomment. Maybe you can use the same?

**Comment by little-brother** [comment]
Why not?
Does DB4S support multiline comments? `/* select * from */`
I didn't find any shortcuts for comments in their docs.

**Comment by jungle-boogie** [comment]
No, not multi line.

ctrl+/ does `--` on each line in DB4S

**Comment by little-brother** [comment]
`Ctrl + /` to comment/uncomment a block.
Also an `Comment`-item was added to a popup menu in Editor.

Only single line comments are supported.
