### ISSUE TITLE
Append file extension based on option selected

### ISSUE THREAD

**Issue by jungle-boogie** [little-brother/sqlite-gui#34]
Hi,

I think export option in `sqlite-gui` should automatically append the file extension to the file name. 

In this example, the file name doesn't have `.csv` appended to it.

1. Open tool
2. Open database
3. Run query
4. Select results
5. Right-click and choose "export to csv"
6. Type in file name
7. Click save
8. Review file in Windows Explorer and notice file name does not have extension

I would expect the file extension present on the export.

Also, Tools > Export as CSV file doesn't append the file extension to the file that's exported.

It looks like `.sql` is also absent when exporting files.

Appending file extensions is a standard Windows behavior when saving files.

Thanks!

**Comment by little-brother** [comment]
Fixed.
