### ISSUE TITLE
Can't ctrl+backspace to delete editor name

### ISSUE THREAD

**Issue by jungle-boogie** [little-brother/sqlite-gui#35]
Hi,

In all GUI applications I use, I can press ctrl+backspace to delete the word behind the cursor.

With `sqlite-gui`, double-clicking an editor allows you to rename it, but ctrl+backspace doesn't delete the text. Instead some weird character is put there.

Please consider supporting ctrl+backspace to rename tabs.

Thanks!

**Comment by little-brother** [comment]
The same as #36. I'll fix it.

**Comment by little-brother** [comment]
Done.
