### ISSUE TITLE
Can't ctrl+a in editor tab names

### ISSUE THREAD

**Issue by jungle-boogie** [little-brother/sqlite-gui#36]
Hi,

ctrl+a does not highlight all text in an editor tab when you're trying to rename it.

1. Open sqlite-gui
2. Double click tab name
3. Notice you're in edit mode
4. Press ctrl+a and notice the text is not highlighted

In https://github.com/little-brother/sqlite-gui/issues/20 you enhanced the ability to use ctrl+a in many places, so this would further improve `sqlite-gui`,

Thanks!

**Comment by little-brother** [comment]
Thanks. I'll fix it. There are another places with the similar behaviour e.g. when rename an item in a navigation tree.
The cause of it is a standard Windows edit control doesn't support this combination.

**Comment by jungle-boogie** [comment]
Understood that there are places outside `sqlite-gui`'s hands to control things.

**Comment by little-brother** [comment]
Done.
