### ISSUE TITLE
Editor tabs still holding on to database

### ISSUE THREAD

**Issue by jungle-boogie** [little-brother/sqlite-gui#37]
Hi,

Similar to https://github.com/little-brother/sqlite-gui/issues/18

Something in `sqlite-gui` is still holding on to the database after it's closed in the app. As a result, I can't delete or rename my database file. I haven't yet tracked down what's causing this.

**Comment by jungle-boogie** [comment]
I think the editor tabs are keeping the database in use.

1. Open `sqlite-gui`
2. Open database
3. Run query in new editor tab
4. Close editor tab
5. Close database but keep `sqlite-gui` open
6. Rename database file

Notice Windows says the file is in use.

I would expect `sqlite-gui` to always release the database once the application closes the file.

**Comment by little-brother** [comment]
Thanks. I forgot to close a connection on a tab closing.

**Comment by little-brother** [comment]
Fixed.
