### ISSUE TITLE
Chart scroll bar doesn't allow you to grab it

### ISSUE THREAD

**Issue by jungle-boogie** [little-brother/sqlite-gui#38]
Hi,

You've nicely improved the charting ability in `sqlite-gui` - thank you very much!

I like that I can scroll the chart downwards and see all data, but the scroll bar on the right doesn't actually allow me to click and drag it.
I can use the mouse wheel to go up and down, but I would expect the ability to click and drag the scroll bar - just like we can on any Windows application.

Please consider allowing the scroll bar to be clicked and dragged.

Thanks!

**Comment by little-brother** [comment]
Thanks. I reproduced a bug.

**Comment by little-brother** [comment]
There is another issue: the scroll stay for lines if type was changed from `bars` with the scroll.

> You've nicely improved the charting ability 

Please check - https://github.com/little-brother/sqlite-gui/discussions/40

**Comment by little-brother** [comment]
Fixed.
