### ISSUE TITLE
Database comparison broken

### ISSUE THREAD

**Issue by jungle-boogie** [little-brother/sqlite-gui#43]
Hi,

I don't know what the database comparison does under tools, but it doesn't seem to do anything useful.

1. Open `sqlite-gui` with the bookstore database
2. Go to tool > database comparison
3.  Choose any other database.
4. Notice this message:

```
---------------------------
Info
---------------------------
No differences found
---------------------------
OK   
---------------------------
```

How could there not be any differences between the two unique databases? The `compare schema` option seems to work fine.

**Comment by little-brother** [comment]
There are two type of comparison: by structure and by data. If structures are different then they can't be compared by data and you got `No differences found`. Pehaps I should change something to avoid this omission.

**Comment by jungle-boogie** [comment]
Yes, maybe all that is needed is a more clear message.

**Comment by little-brother** [comment]
The message was changed.
