### ISSUE TITLE
Encrypted database kept active

### ISSUE THREAD

**Issue by jungle-boogie** [little-brother/sqlite-gui#45]
Hi,

If I open an unencrypted database, encrypted it, close it, and reopen it, I can read the data without a password prompt.

1. Open `sqlite-gui`
2. Open a database
3. Database > set encryption
4. Use default password and type in password
5. Click ok
6. Don't backup database
7. Notice SQL logo changes to cyan color
8. Close database but keep `sqlite-gui` open
9. Open same database you used in step 2
10. Notice there is no password prompt and the `sqlite-gui` icon changed to cyan color

I think this is another instance where the database is kept open/in memory, even though `sqlite-gui` shows it closed.

Thanks!

**Comment by little-brother** [comment]
This a feature. The password is stored in memory until the app is exited.

**Comment by jungle-boogie** [comment]
Maybe it would be best to put a timeout on that feature of 5 minutes, then purge the passphrase from memory.

**Comment by little-brother** [comment]
> 5 minutes, then purge the passphrase from memory

It's an unpredictable behaviour. 

The app is run fast, so I don't know why someone should want to stay it idle with an opened secret data.

**Comment by jungle-boogie** [comment]
Hi,

I don’t know why the app would retain the pasphrase after the database that
was encrypted is closed but before the app is closed.

Why is that expected behavior?

**Comment by little-brother** [comment]
Yeah, I made it for conveniences. Maybe it should be turn off by default.

**Comment by jungle-boogie** [comment]
You could consider making it an option. "Retain encrypted passphase in memory" or something, but I'd recommend having it off by default.

**Comment by little-brother** [comment]
Added the new option in `Settings`.  By default passwords aren't stored.
