### ISSUE TITLE
Thank you!

### ISSUE THREAD

**Issue by jungle-boogie** [little-brother/sqlite-gui#46]
Hello,

I wanted to thank you for working with me on all the bug reports. You response to the issues has been outstanding and I appreciate your willingness to continue improving `sqlite-gui`.

You're doing a great job and this tool has improved greatly from when I first started using it - which is all the way back in September 2020!

Keep up the great work.

Best,
j.b.

**Comment by little-brother** [comment]
Thanks for your kind words and your participation in the app development by issues. It's really helpful.

I try to follow two rules in this app development: 
1. No long-time open issues
2. A next release have to be not just bug fixes and contain a new feature(s).

That is why a new release is coming soon :)

**Comment by jungle-boogie** [comment]
Looking forward to the new features!

**Comment by little-brother** [comment]
Released :)
