### ISSUE TITLE
Copy column names from tree

### ISSUE THREAD

**Issue by jungle-boogie** [little-brother/sqlite-gui#47]
Hi,

Sometimes I don't want to type the column names that I'm interested in querying from. It would be nice if I could copy the column name with ctrl+c and paste it into the editor window.

This is mostly working, but it will also copy over the datatype, so that has to be deleted as well.

For example, `EventCode: TEXT` It would be nice if it would just copy `EventCode`, then I copy paste that into the editor/terminal.

alternatively, is it possible for auto complete to look at column names?

Thanks!

**Comment by little-brother** [comment]
Yeah, it's a bug.

To avoid type a column name you can use `alias` e.g. `b`:
```
select * from books b
-->
select b.id, b.<autocomplete should appear here>  from books b
```

**Comment by little-brother** [comment]
Fixed.

Starting from this release you can drag-n-drop tree items to an editor as in SQLiteStudio and DB4S.
Also dragging with `Ctrl` you can generate `DML`-statement.
