### ISSUE TITLE
Table names present with auto complete

### ISSUE THREAD

**Issue by jungle-boogie** [little-brother/sqlite-gui#48]
Hi,

When a database was opened and then closed, auto complete can look at the table names.

1. Open `sqlite-gui.1.5.4`
2. Open database bookstore.sqlite
3. Run simple query
4. Close database with close button
5. Type `select * from ` and notice tables appear in the drop down menu

I wouldn't expect table names to be present, since the database was closed.

Thanks!

**Comment by little-brother** [comment]
I agree for security reasons. It will be fixed.

**Comment by little-brother** [comment]
Fixed.
