### ISSUE TITLE
Option to include rowid

### ISSUE THREAD

**Issue by jungle-boogie** [little-brother/sqlite-gui#49]
Hi,

Something for you to consider as a new setting...

Maybe an option to show the rowID when browsing the data checkbox could be added. 

DB4S has an option to show the rowID if you right-click on the header when browsing the data. You don't see the rowID if your query doesn't have it.

thanks!

**Comment by little-brother** [comment]
Actually a data grid in "Edit data" dialog has rowid column with zero width (so it's hidden) for `update` and `delete` operations.
For what reason would anyone want to see the rowid? I don't want to overcomplicate by rarely used features.

**Comment by jungle-boogie** [comment]
You're right. I can't think of a compelling reason to want to include it in the app. If someone wants to know the rowID, they can include it in their query.
