### ISSUE TITLE
Double-click broken for text in 'single quotes'

### ISSUE THREAD

**Issue by jungle-boogie** [little-brother/sqlite-gui#50]
Hi,

Using sqlite-gui, the editor seems broken when you try to double-click text in single quotes.

Type
```
'hello'
```
in the editor and double-click hello. You'll notice you cannot, it will select the single quote on the right.

I would expect double clicking to function when there are single quotes around a word.

**Comment by little-brother** [comment]
Yeah, it's a bug. Windows 7 `Richedit`-component bug :(

**Comment by little-brother** [comment]
Fixed by duct tape.
