### ISSUE TITLE
Paste text as pain text

### ISSUE THREAD

**Issue by jungle-boogie** [little-brother/sqlite-gui#51]
Hi,

Sometimes I need to use MS Excel to open a file and extract info from it. When I paste it in `sqlite-gui`, I would expect it to paste as a plain text file. Instead, it's carrying over the formatting from MS Excel. That's not needed.

Please consider allowing pasting as plain text.

Thanks!

**Comment by little-brother** [comment]
There is nothing to consider. It's a bug and it should be fixed.

**Comment by little-brother** [comment]
Fixed.
