### ISSUE TITLE
Auto complete column names

### ISSUE THREAD

**Issue by jungle-boogie** [little-brother/sqlite-gui#52]
Hi,

Similar to #47...

Is it possible to auto complete the column names while typing the name out?

SQL Server seems to support this.

Thanks!

**Comment by little-brother** [comment]
Can you provide a short video how it works?
I think, it's possible but it could be a little complicated.

**Comment by jungle-boogie** [comment]
Hi,

Yes, I should be able to. I'll likely provide that via email to you.

**Comment by little-brother** [comment]
lb-im@ya.ru
The main question: what does SQLServer (Manager?) suggest when I typed `select ` (there is no table name).

**Comment by jungle-boogie** [comment]
`select * from` won't show any table names. You need to type out a partial table name, make a selection of which table to use, then type in a partial column name.

For what it's worth, It seems DB4S operates similar to SQL Server Management Studio.

**Comment by little-brother** [comment]
Implemented. 
The first version can be a little bit buggish and annoying.
