### ISSUE TITLE
Copy/paste to include header request

### ISSUE THREAD

**Issue by jungle-boogie** [little-brother/sqlite-gui#53]
Hi,

I like that you can save the results from a query as a csv file and it includes the header.

This is a request to have the the header present when you copy to the clipboard.

This is copy/paste and notice there is no header... :(
```
1,Steelheart,Brandon Sanderson,978-0385743563,5.0,3
2,All Our Yesterdays,Cristin Terrill,978-1423176374,7.3,10
3,Life After Life,Jill McCorkle,978-1616203221,2.82,4
4,Life After Life,Kate Atkinson,978-0316176491,8.1,5
5,Foundation,Isaac Asimov,978-0553293357,12.7,8
```

Alternatively, maybe there can be a right-click option to copy data with header.

Thanks!

**Comment by little-brother** [comment]
What about with `Ctrl`?

**Comment by jungle-boogie** [comment]
`ctrl`+`c` doesn't copy the header info, either.

**Comment by little-brother** [comment]
Yeah, I suggested `Ctrl` + Menu item click. But it conflicted with `Ctrl + C`. 
Maybe `Shift` + Menu item or `Shift + Ctrl + C` to copy with header, will be good?

**Comment by jungle-boogie** [comment]
Why not just another menu option with right-click?

**Comment by little-brother** [comment]
I don't like large menus/toolbars :) 
`Crtl + Shift + C` already used by DB4S, so it can be reasonably.

**Comment by little-brother** [comment]
Done.
