### ISSUE TITLE
Include vsv

### ISSUE THREAD

**Issue by jungle-boogie** [little-brother/sqlite-gui#56]
hi,

Since `sqlite-gui` is 32 bit only (right now), could you please compile and include the vsv extension?

http://www.dessus.com/files/vsv.c
which looks the same/similar as this:
https://www.sqlite.org/src/file?name=ext/misc/csv.c&ci=trunk

**Comment by jungle-boogie** [comment]
If sqlite-gui were 64bit, I'd be able to use this dll:
https://github.com/nalgeon/sqlean/blob/main/docs/vsv.md

**Comment by little-brother** [comment]
Ok. You can already download it here - https://disk.yandex.ru/d/17JScOaKYkoXsw
