### ISSUE TITLE
Directory held active after closing database

### ISSUE THREAD

**Issue by jungle-boogie** [little-brother/sqlite-gui#57]
Hi,

Similar issues:
#48, #37, #18

1. Open `sqlite-gui`
2. Open database
3. Execute query
4. Close database
5. Delete database from directory
6. Go up a directory to where the database was store
7. Attempt to delete the directory
8. Notice Windows will say the directory is in use and you cannot delete it
9. Close `sqlite-gui`
10. Attempt to delete the directory that you attempted to delete in step 8
11. Notice you are now able to delete the directory

I would expect to be able to delete the directory my database was in, because the database has been closed and itself has been deleted.

thanks!

**Comment by little-brother** [comment]
Yes, it's a bug. A very strange bug. I need time to investigate cause.

**Comment by little-brother** [comment]
Fixed.
