### ISSUE TITLE
Export option when there is more than 10,000 records

### ISSUE THREAD

**Issue by jungle-boogie** [little-brother/sqlite-gui#58]
Hi,

I know if a query returns more than 10,000 records, the data is cut and not displayed.

Could you please consider adding a feature to export the data to a csv file if it displays more than 10,000 records?

Maybe there could be an option added to the 'export data of table/view to CSV file'? Or a right-click on the results tab when has the (Cut to 1000 rows) text present and a "export to csv file".

OR `sqlite-gui` could be supported to allow for 10k+ records! :)

Thanks!

**Comment by little-brother** [comment]
1. You can change the row limitation in Settings. 10K is a data grid limitation: the grid can show unlimited records but it will be visibile slow.
2. You can export any table/view to csv by `Tools > Exports as CSV file`.

I don't see how to make a GUI with a simple choice: `Export only cutted rows` and `Export all rows` (this requires rerun the query). Maybe gui should show dialog on export to check/uncheck desired columns and with choice selector if rows were cutted.

**Comment by jungle-boogie** [comment]
1. Ah, that's neat! I didn't know about that setting.
2. Yes, you can export a table/view. But not results of a query which are over 10,000+ records. Maybe 1 above resolves this.

> Maybe gui should show dialog on export to check/uncheck desired columns and with choice selector if rows were cutted.

That would be neat to select which columns you want to include, but the query could be updated to reflect that as well.

**Comment by little-brother** [comment]
Fixed.
