### ISSUE TITLE
Display highlighted row number 

### ISSUE THREAD

**Issue by jungle-boogie** [little-brother/sqlite-gui#59]
Hi,

For the editor, you added in a line and character count. See #23

It would be nice to have the row number displayed when you're clicking around the in the results of your query. I think this could go in between the line number and the elapsed time spot.

thanks!

**Comment by jungle-boogie** [comment]
When you double-click a results row, maybe the row number could be included in there as well.

**Comment by little-brother** [comment]
To show row number in the status bar can be ambiguous if there are more than one rows. What problem does this improvement should solve?

The row number in `Row view/edit`-dialog will be added.

**Comment by jungle-boogie** [comment]
You're right, if someone selected non-adjacent records in the results tab, it would be ambiguous.

Could it be hidden in that case and only present if 1 or more adjacent records are selected? Then you could show `1-5` or similar message.

**Comment by little-brother** [comment]
The row number was added to statusbar. If more than one line is selected then the first row index show.
