### ISSUE TITLE
Include option to set delimiter at export of results

### ISSUE THREAD

**Issue by jungle-boogie** [little-brother/sqlite-gui#60]
Hi,

The `export data of table/view to CSV file` gives you the option to specify the delimiter and line type.

When you run a query, and you want to export, you don't have that option. With #53, you can at least select all, copy with header and paste, but it would be nice to have an option to set the delimiter on export of results.

I see two options:
1. A new global setting for exporting to csv
2. A new setting specific for exporting results to csv

Thanks!

**Comment by little-brother** [comment]
This export uses the last csv export setting. Also you can change these options through terminal by `.set`-command:
```
.set param value
.set csv-export-delimiter - one of 0, 1, 2, 3 (equals to `,`, `;`, `Tab` and `|`)
csv-export-is-columns 0 or 1
csv-export-is-unix-line 0 or 1
```

**Comment by jungle-boogie** [comment]
You can't use the export option until you export data. There's no way to use the dialog box to set and save settings.

**Comment by jungle-boogie** [comment]
> Also you can change these options through terminal by .set-command:

That's a neat trick!! Thank you!

**Comment by little-brother** [comment]
Added a point to `Tips` for this.
