### ISSUE TITLE
Double-clicking word in editor broken

### ISSUE THREAD

**Issue by jungle-boogie** [little-brother/sqlite-gui#63]
Hello,

With `sqlite-gui` 1.5.7, you cannot double-click a word to highlight it. It doesn't matter if it doesn't have any quotes, double quotes or single quotes - you cannot highlight it.

1. Open gui app
2. In editor type `hello`
3. Double-click word and notice it is not highlighting as you expect

This seems to be a regression in the latest app.

**Comment by jungle-boogie** [comment]
If it's related to `ctrl`+`F`, it seems you have to press that key combination a couple times occasionally to get the find dialog to pop up.

**Comment by little-brother** [comment]
> Could it be related to this enhancement: Highlight all occurrences of selected word in editor
It's related :( `Ctr+F` was broken too.

**Comment by jungle-boogie** [comment]
> It's related :( `Ctr+F` was broken too.

While you're researching the `ctrl+f`, what about adding a find and replace option? :) :)

**Comment by little-brother** [comment]
(ノಠ益ಠ)ノ彡┻━┻

**Comment by little-brother** [comment]
Double click was fixed. `Replace` option was added.

**Comment by jungle-boogie** [comment]
The double-clicking seems to not always work correctly.

I think if a sql statement has an error in it, double-clicking won't function after you run the query.

**Comment by jungle-boogie** [comment]
Hi,

Have you had a chance to review this?

It may be statements with_underscores causing problems.

>

**Comment by little-brother** [comment]
Could you provide an query example with the broken selection?

P.S. Yeah, I don't get a notification :(

**Comment by little-brother** [comment]
I removed the standard behaviour by custom and added `Ctrl + Click` to select entire quoted text.
