### ISSUE TITLE
Add row always at bottom of data

### ISSUE THREAD

**Issue by jungle-boogie** [little-brother/sqlite-gui#64]
Hi,

Regardless of the highlighted row in the edit data for a table, it always inserts the new data at the end of the existing records. I would expect data to be inserted where the highlighted line is present.

Also, maybe three buttons needed? `Save and new` seems like you always needed to insert new records. Maybe there can be a `save and close`, `save and new` and `cancel`.

**Comment by little-brother** [comment]
> I would expect data to be inserted where the highlighted line is present.

**Comment by jungle-boogie** [comment]
I understand a simple GUI is desired, but after inserting a record, there's not a way to close without pressing 'cancel'. Maybe all that's needed is to change the label to 'close'.

How will i know that after typing in all my data, cancel is the same as close? I know I don't want to insert any new records, but what do I do now?

**Comment by little-brother** [comment]
Ok, I'll change `Cancel` to `Close` :) But imho they are same.

**Comment by jungle-boogie** [comment]
Maybe it's a language barrier but cancel and close definitely have different meanings.

**Comment by little-brother** [comment]
`Cancel` was renamed to `Close`.
