### ISSUE TITLE
No grid coloring when max output is set to 0

### ISSUE THREAD

**Issue by jungle-boogie** [little-brother/sqlite-gui#66]
Hi,

When the max rows in result output is set to `0`, I noticed the grid is not colored. It doesn't matter if the results are 10 records or 10,000, there's no coloring at all.

Is that expected?

Thanks!

**Comment by little-brother** [comment]
Yes. With unlimited rows (`row-limit=0`) I can't forecast how much memory I should allocate for colors.
Maybe it will be changed in next releases.

**Comment by jungle-boogie** [comment]
Understood. Maybe, if you want, you could have it color only 10-15 records at a time. Otherwise, I think it's acceptable to have it disabled.

**Comment by little-brother** [comment]
There is nothing to change. Let it be a feature and is not a bug.

**Comment by jungle-boogie** [comment]
Good with me. Good call.
