### ISSUE TITLE
Adjust colmn headers based on the name

### ISSUE THREAD

**Issue by jungle-boogie** [little-brother/sqlite-gui#68]
Hi,

`select price,available from books`

If you double-click on the double arrows that happen when you're on the column header separator, the column widths are spaced based on the contents of the column. Which means you cannot read the column headers 'price' or 'available`.

It would be nice to have the column header spaced based on the name of the column and the contents.

Thanks!

**Comment by little-brother** [comment]
Hmm, I don't know about this trick. It's a default behaviour of a Windows component. I'll try to fix it.

**Comment by jungle-boogie** [comment]
I think MS Excel will size according to the header and contents of the cells. That may be because it doesn't really distinguish between a header and a regular cell.

**Comment by little-brother** [comment]
Fixed.
