### ISSUE TITLE
Error opening database

### ISSUE THREAD

**Issue by Dominiquini** [little-brother/sqlite-gui#7]
I tried to open some database and receive this error:

> "attached databases must use the same text encoding as main database"

The sabe database was opened in "SQLiteStudio"

Thanks.

**Comment by little-brother** [comment]
Most likely your database uses `utf16` encoding that currently unsupported by sqlite-gui.
You can check it by running `pragma encoding`. 

The reason for the error: sqlite-gui attachs `prefs.sqlite` as `preferences` on startup and `prefs.sqlite` has `utf8` encoding.
I'll try to get rid of this behaviour, but before I should verify that it make sense and the app can show `utf16` data correctly.

Thanks for issue report!

**Comment by Dominiquini** [comment]
Yes, the database is encoded in "UTF-16le".

Thanks.

**Comment by little-brother** [comment]
Fixed.
