### ISSUE TITLE
Manually check for update?

### ISSUE THREAD

**Issue by jungle-boogie** [little-brother/sqlite-gui#70]
Hi,

For the first time, I opened `sqlite-gui` and was advised there was a new download! That's a neat feature. I typically see releases before opening the app and download ahead of time, so I already know about it.

It's also nice that you don't prompt the user each and every time there is a new download. If I say 'no' to version X but I want to periodically check and see if there's a new version, do you have a menu item to check for that? Deleting `prefs.sqlite` will, of course, prompt the user, but that's a little drastic.

Thanks!

**Comment by jungle-boogie** [comment]
And another question...

If I'm prompted to download 1.6.0 from 1.5.9, and I copy my `prefs.sqlite` to 1.6.0, will it know to check for `1.6.1`? IOW, does `check-update` care about the version number?

**Comment by little-brother** [comment]
> If I say 'no' to version X

The question will be repeat after 24+ hour. The last check stores in `last-update-check` (`YYYYMMYY` ) . So app checks the update  once a day or less until the user's version matches the current release  (it doesn't matter what the release user has). 
This behaviour was introduced in `1.5.6`.

`check-update` is only `false`/`true`-flag corresponding to "Check update automatically"-option in Settings.
