### ISSUE TITLE
Window and UI observations

### ISSUE THREAD

**Issue by jungle-boogie** [little-brother/sqlite-gui#71]
Hi,

Sometimes I need to make the editor tab larger to see my query text easier, so I move the results pane down.

Two things...

1. It seems the area that activates moving the results pane is very narrow and difficult to find. If I have only 1 results tab, could the large area to the right be used as the way to adjust it?

![resize-pane](https://user-images.githubusercontent.com/1111743/128248512-a0c6d1a5-8d8d-405f-9c44-9747175bd87c.png)

2. If I resize the whole app, things don't seem to scale in proportion to the pane sizes. It's hard to explain, but I think you'll see what I'm talking about if you compare `sqlite-gui` to `DB4S`.

**Comment by little-brother** [comment]
1. Worth considering, looks reasonable.
2. At this moment the editor stores own height and the result panel is increased on resize. 
    Maybe they should change proportionally.

**Comment by little-brother** [comment]
Done.
