### ISSUE TITLE
Failed to import csv file

### ISSUE THREAD

**Issue by jungle-boogie** [little-brother/sqlite-gui#72]
Hi,

I am having issues importing a csv file into a database. The table is empty and I've tried with LF and CRLF files but both fail.

I was able to import the csv with sqlite cli without any issue.

```
---------------------------
Error
---------------------------
Error to open file
---------------------------
OK   
---------------------------
```

**Comment by little-brother** [comment]
Thanks. It's a bug.

**Comment by little-brother** [comment]
Fixed.
