### ISSUE TITLE
Drag and drop sql files

### ISSUE THREAD

**Issue by jungle-boogie** [little-brother/sqlite-gui#73]
Hi,

Many times I already have sql queries saved in txt/sql files that I want to get the query and run. It would be nice if I could drag the sql query file and drop into the editor of `sqlite-gui`

This is something I can do with MSSQL, HediSQL, and DB Browser for SQLite. I understand `sqlite-gui` is more lightweight than all of those, so this may make your tool too complex.

Thanks for the consideration!

**Comment by little-brother** [comment]
Done.

**Comment by jungle-boogie** [comment]
This only seems to read in a certain number of bytes. The whole file is not loaded and therefore, the sql statement is incorrect.

**Comment by little-brother** [comment]
What size of your file?

**Comment by little-brother** [comment]
Fixed.
