### ISSUE TITLE
Please check existing issues

### ISSUE THREAD

**Issue by jungle-boogie** [little-brother/sqlite-gui#74]
Hi,

Because you've closed the issues, I can't re-open these issues. Please review these issues and re-open/investigate.

https://github.com/little-brother/sqlite-gui/issues/73
https://github.com/little-brother/sqlite-gui/issues/63

Thanks!

**Comment by little-brother** [comment]
Thanks! I reopened them. 
Please, next time create a new issue or report to telegram channel - https://t.me/sqlitegui

**Comment by jungle-boogie** [comment]
I joined the channel but I think it's read-only? I don't see anyway to chat.

**Comment by little-brother** [comment]
Hmm, I thought that I set up the channel correctly. Tomorrow I'll try to fix it.

**Comment by jungle-boogie** [comment]
See attached picture (sending from phone, so I’ll see if picture posts to
GitHub). I see your message but no way to reply to you.

**Comment by little-brother** [comment]
Perhaps, I should create a `group` and not a `channel`.

**Comment by jungle-boogie** [comment]
That seems to work better, but I can only comment on your messages.
