### ISSUE TITLE
Can't query from table with dash

### ISSUE THREAD

**Issue by jungle-boogie** [little-brother/sqlite-gui#77]
hi,

Earlier I said `_` (underscores) cause problems in table queries, but it's actually dashes.

```
drop table if exists foo-bar;

CREATE TABLE if not exists "foo-bar" (
"init" ,
"text" 
);

select * from foo-bar;
```

I can create the table, but I can't drop or or query from it.

**Comment by little-brother** [comment]
Because you need to quote the table name if it contains any non-alphanumeric and lodash chars 
`select * from "foo-bar"`

**Comment by jungle-boogie** [comment]
Good enough with me. happens in sqlite3 cli as well.
