### ISSUE TITLE
Feature: import data from terminal

### ISSUE THREAD

**Issue by jungle-boogie** [little-brother/sqlite-gui#78]
Hi,

It would be neat if sqlite-gui could import a csv file via the terminal.

I have a csv file opened in MS Excel, where I am making the changes. I then import the data into my sqlite database, but it's a few clicks to do the same thing over and over.

Would be neat to do something like `.import --csv --skip 1 /path/to/file.csv table`, just like we can in the cli for SQLite.

**Comment by little-brother** [comment]
Ok, I'll add it, but a little bit later (currently I'm hard working on a small side project).
Also check [this method](https://youtu.be/Pz-BPaL6t4k).

**Comment by jungle-boogie** [comment]
Thanks!

What's your other project? Is it something open source?

**Comment by little-brother** [comment]
Similar to [FQLite](https://github.com/pawlaszczyk/fqlite), but I'm not sure of success.

**Comment by little-brother** [comment]
Done. Export was also added.
