### ISSUE TITLE
no such function: ceil

### ISSUE THREAD

**Issue by nilnewb** [little-brother/sqlite-gui#81]
Using sqlite-gui.1.6.3. I do have an issue when trying to generate data.. I select the fields according to my table, and also select the right foreign keys.. the right type of data etc..
no matter what, I get the pop up error : no such function: ceil
If I generate data without selecting anything (all to none), it adds the rows..
What am I missing ?
(this happens with differents db)

**Comment by little-brother** [comment]
Thanks for report! It's a release bug: sqlite3 with ciphers was built without math functions. 
It will be fixed in the next release. But for now, you can use [`no-ciphers`](https://github.com/little-brother/sqlite-gui/releases/download/1.6.3/sqlite-gui.1.6.3.zip)-version.

**Comment by nilnewb** [comment]
Thank you for your quick answer..
yup the no-cyphers version works!...
Best regards,
E.Nilsson

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by little-brother** [comment]
Fixed.
