### ISSUE TITLE
New SQLite version

### ISSUE THREAD

**Issue by jungle-boogie** [little-brother/sqlite-gui#82]
Hello,

SQLite released version 3.37.0 on 27th of November.
https://sqlite.org/releaselog/3_37_0.html

Would it be possible to have `sqlite-gui` updated with the latest version?

Thanks!

**Comment by jungle-boogie** [comment]
I realize I can drop in a new sqlite3.dll into the directory, but just letting you know about the latest version of SQLite.

**Comment by little-brother** [comment]
I am already working on it :)  
"Create table"-dialog needs "strict"-option. Plus changes related to a new SQLite type - ANY.
