### ISSUE TITLE
Foreign keys bug?

### ISSUE THREAD

**Issue by SilvioGrosso** [little-brother/sqlite-gui#85]
Hello @little-brother 

In all truth, I don't know whether is it a bug or a feature of SQlite 3.37.0?
Please, bear with me :-)

With Db Browser and SqliteStudio the following code works fine in that it prevents me to insert values that are not "referenced" (foreign key table).

Here is my SQL code:
create table articles(
id integer not null,
fruit text primary key
);

insert into articles (id, fruit) values 
(1, 'arance'), 
(2, 'banane'), 
(3, 'mele'), 
(4, 'pere'), 
(5, 'prugne'), 
(6, 'uva');

create table buyers (
id integer primary key, 
buyer text, 
fruit text, 
price integer, 
FOREIGN KEY (fruit) 
REFERENCES articles(fruit)
);

insert into buyers (id, buyer, fruit, price) values 
(1, 'Silvio', 'mele', 1500), 
(2, 'Marco', 'pere', 1600), 
(3, 'Stefano', 'arance', 1800),
(4, 'Rosa', 'mele', 1520);

--now here comes the problem, with the following SQL code:
insert into buyers values (5, 'Marco', **'fragole'**, 1600); 

With the fruit 'fragole" both Db browser and SqliteStudio throw an error **"Foreign key constraint failed"**
On the contrary Sqlite-gui accepts this value (and many others as regards "fruit"). 
In all truth, this is a bit strange to me...
It looks like the foreign key (for the value fruit) it is not checked...

If i check the Database diagram it looks like there is indeed a foreign key applied as a check for the values (fruit) to insert or not:
![immagine](https://user-images.githubusercontent.com/33007383/146692488-ddee4442-fa8d-40e0-8fe0-4b3dcc94b167.png)

BTW, with both softwares, in their GUIs, there is a drop-down botton where you can pick the values for fruits. 
As a  consequence, you can not be wrong by chosing a different fruit (e.g. "fragole") :-)

![immagine](https://user-images.githubusercontent.com/33007383/146692678-1f4cfe30-252c-4145-a6a3-0b173afd1ff0.png)

**Comment by little-brother** [comment]
DB4S and SQLiteStudio use `pragma foreign_keys = on` (execute `pragma foreign_keys` to verify it`).
The foreign key check is disabled in SQLite by default and sqlite-gui doesn't modify this (and any others) setting on startup. You can change this behaviour in Settings by set up  `Execute on connection`  to `pragma foreign_keys = on`.

**Comment by SilvioGrosso** [comment]
Ok. Now it works :-)

I was pretty much sure it was a feature and not a bug of Sqlite-gui.
SQlite.exe (v. 3.37.0) behaved the same.
In the long past I have read about this, but now I have completely forgot to apply this setting :-)

**Comment by little-brother** [comment]
Ok :)
