### ISSUE TITLE
sqlite-gui: unable to import csv file (Windows 10)

### ISSUE THREAD

**Issue by SilvioGrosso** [little-brother/sqlite-gui#86]
Hello @little-brother 

Windows 10 (home edition)
sqlite-gui x64

I have tried to import some CSV tables created both by LibreOffice Calc and PgAdmin (PostgreSQL GUIs)
Both Db Browser and SqliteStudio import these CSV files without problems whereas sqlite-gui always fails. It throws up an error which is quite meaningless in order to understand what's going on :-)
I have tried various settings to no avail.

![immagine](https://user-images.githubusercontent.com/33007383/146817531-4bd08806-9efc-48e8-9dfd-89edb5557c63.png)

For instance, create 2 tables (anfi_2020 and Induff_2020) with the following SQL code:
CREATE TABLE INDUFF_2020 (
ID_PROG INTEGER NOT NULL PRIMARY KEY,
NAME_TECHNICIAN TEXT,
COMPAGNO TEXT,
N_VERBALE TEXT,
DATA DATE,
INIZIO_ORE NUMERIC,
FINE_ORE NUMERIC,
ORE_TOTALI_SITI NUMERIC,
ORE_OPERAZIONE REAL,
PESO_VERBALE REAL,
PESO_RIGA REAL,
COMUNE TEXT,
PROVINCIA TEXT,
ISTAT_CODICE TEXT,
LATITUDINE TEXT,
LONGITUDINE TEXT,
TIPOLOGY_AREA TEXT,
N_HA REAL,
N_PIANTE INTEGER,
N_SITES INTEGER,
N_HOURS_INSPECTING REAL,
HOURLY_COST_INSPECTING REAL,
VISUAL_TOTAL_COST REAL,
NOME_LATINO TEXT,
CODICE_PIANTA TEXT,
ANOPL INTEGER,
BURS INTEGER,
DIA INTEGER,
EPITR INTEGER,
ERST INTEGER,
FD INTEGER,
GEO INTEGER,
GIB INTEGER,
GLOB INTEGER,
MON INTEGER,
PIS INTEGER,
POM INTEGER,
POP INTEGER,
PSA INTEGER,
RAL INTEGER,
ST INTEGER,
XF INTEGER,
AROBU INTEGER,
CMS INTEGER,
BACTR INTEGER,
MELG INTEGER,
SPOD INTEGER,
CER INTEGER,
EA INTEGER,
PPV INTEGER,
PRAM INTEGER,
ORGANISMI_CONTEGGIO INTEGER,
N_SAMPLES_TAKEN INTEGER,
N_HOURS_COLLECTING REAL,
HOURLY_COST_COLLECTING REAL,
SAMPLING_TOTAL_COST REAL,
SFR_SAMPLE_CODE TEXT,
CONSUMMABLE_COST REAL,
TIPOLOGY_SAMPLE TEXT,
ON_CAMPIONE TEXT,
N_TRAP_PLACED_OR_COLLECTED_OR_SOST INTEGER,
N_TRAPS_PLACED INTEGER,
TIPOLOGY_OF_TRAPS TEXT,
SFR_TRAP_CODE TEXT,
COST_OF_TRAPS REAL,
N_ATTRACTANS_PLACED INTEGER,
COST_OF_ATTRACTANS REAL,
N_HOURS_TRAPS_PLACED REAL,
HOURLY_COST_TRAPS_PLACED REAL,
TRAPS_PLACED_TOTAL_COST REAL,
N_TRAPS_CONTROLLED INTEGER,
N_HOURS_TRAPS_CONTROLLED REAL,
HOURLY_COST_TRAPS_CONTROLLED REAL,
N_TRAPS_COLLECTED INTEGER,
N_HOURS_TRAPS_COLLECTED REAL,
HOURLY_COST_TRAPS_COLLECTED REAL,
COLLECTING_TOTAL_COST REAL,
ON_TRAPPOLA TEXT,
ON_TEST TEXT,
N_TEST INTEGER,
SFR_CODE TEXT,
TIPOLOGY_SAMPLES TEXT,
TIPOLOGY_TEST TEXT,
UNIT_COST REAL,
TOTAL_COST_TESTING REAL,
N_POSITIVE_TESTS INTEGER,
RESULTS TEXT,
POS_SE_POP TEXT,
POS_SE_ANOPL TEXT,
NOTE TEXT
);

CREATE TABLE ANFI_2020 (
SFR_ID    TEXT NOT NULL PRIMARY KEY,
DATA_CONSEGNA     DATE,
MATRICE_COD     TEXT,
MATRICE_DESCR    TEXT,
CONFERENTE    TEXT,
PROVENIENZA    TEXT,
TEL_CONF TEXT,    
EMAIL    TEXT,
INDIRIZZO_CONFER    TEXT,
NOME_AZIENDA TEXT,    
TEL_AZ    TEXT,
INDIRIZZO_AZ    TEXT,
COM_AZIENDA    TEXT,
SINTOMI     TEXT,
OSSERVAZIONI_VARIE    TEXT,
SINTOMI_INDUFF TEXT,
N_CAMPIONE_INDUFF    INTEGER,
ON_INDUFF_PRIMARIO    TEXT,
ESITO_INDUFF_PRIMARIO    TEXT,
DIAGNOSI_SINTETICA_PRINCIPALE    TEXT,
DIAGNOSI_COMMENTATA    TEXT,
TERAPIA    TEXT,
TECNICO_SFR_RICEVENTE    TEXT,
LABORATORIO_LAVORAZIONE    TEXT,
DATA_ESITO     DATE,
ESITO_MEZZO    TEXT);

**Here is a ZIP file with 2 CSV files (for the 2 corresponding tables,** ten rows each): UTF-8; comma as separators for columns which is stored on Microsoft OneDrive (no account needed to download it...):
https://1drv.ms/u/s!AjEV_9wBPHINgoYKbWXj9js6B50zAg?e=QD3u4I

BTW, with CSV files I have always opt for Db Browser which is incredibly smart to import them :-)
In the past this was one of the reasons for which I have stopped working with SqliteStudio...

**Comment by SilvioGrosso** [comment]
BTW, here is a video where I have recorded all steps to import these 2 CSV into Db Browser. In case it might be useful :-)

https://user-images.githubusercontent.com/33007383/146820388-b5534302-54d6-43f6-acd1-1b0d105bf257.mp4

As a personal feature request, It would be useful to have an option in sqlite-gui to import the empty records and cast them as "NULL" (as type). Maybe it is already possible...
It is the default option with Db Browser (all empty records become NULL in the new table) when you import CSV files

Thanks a lot!

**Comment by little-brother** [comment]
1. `ANFI_2020_PGADMIN_UTF-8.csv`: quoted columns raise the import error. It's a bug.
2. `INDUFF_2020_vers-4_PGADMIN_UTF-8.csv` has duplicate column `SFR SAMPLE CODE`. Maybe sqlite-gui should request user and add something to duplicate e.g. `SFR SAMPLE CODE2`. I should think out how to implement it.
3. ` import the empty records`: presently `sqlite-gui` import empty rows as `NULL`-record. But `ignore empty rows`-option can be added.

**Comment by SilvioGrosso** [comment]
Hello @little-brother 

1)
> INDUFF_2020_vers-4_PGADMIN_UTF-8.csv has duplicate column SFR SAMPLE CODE. Maybe sqlite-gui should request user and add something to duplicate e.g. SFR SAMPLE CODE2. I should think out how to implement it.

How strange :-)
Importing CSV files is quite complicated because they are often quite "convoluted"
These 2 CSV come from a Spreadsheet (LibreOffice Calc) where you can indeed name 2 columns similarly (sfr sample code).
I have never thougtht about this problem because I have alyways assumed that, by clicking "column names in first line" the importers was going to ignore this duplication. 
With PgAdmin and other softwares (Db Browser, SqliteStudio) I have always checked "column name first line" and I have never realized it could be a problem since the process worked as expected :-)
My SQL code to create the 2 tables (Anfi - Induff) has no duplication as regards the names of the columns

2)
BTW, If I delete all " (quotes) with Notepad++ Sqlite-gui is **still unable** to import the CSV.  
Maybe there is another bug?
The " (quote) is replaced by Notepad++ with a space (maybe this is the problem?). 
See following screenshot with the CSV not quoted by "

![immagine](https://user-images.githubusercontent.com/33007383/146982044-30ed8b68-b47b-41e9-8a2a-3777e577a7ec.png)


3) As regards empty rows I suppose they should skipped and not imported in the table.
I was referring to cast empty "cells" as NULL. 
In my spreadheets (LibreOffice Calc) I have plenty of cells with empty data but I would prefert to treat them as NULL in the database new table 

For instance this CSV:
NAME|SURNAME
marco|
silvio|grosso

Might be imported as:
NAME|SURNAME
marco|**NULL**
silvio|grosso

**Comment by SilvioGrosso** [comment]
Hello @little-brother 

I suppose there is another little bug in the importer as regards the "messages" of the windows which are quite misleading...

Paste the following code:
CREATE TABLE users
(id integer not null primary key,
name text,
surname text unique,
age integer check (age > 25 AND age < 50))
--pay attention to the check for age :-)

With the following CSV data the import should fail (age is > 50)
id,name,surname,age
1,silvio,grottino,55

Instead Sqlite-gui informas me that is has imported one row! :
![immagine](https://user-images.githubusercontent.com/33007383/146984996-c50e4715-04b2-4975-b838-04f9627cbcea.png)
But if you check the table **NO** data has been imported which is correct, due to the check :-)
Therefore the message about is not correct.

This is the message with Db Browser for the same CSV:

![immagine](https://user-images.githubusercontent.com/33007383/146984703-5da7acbc-77f6-4f4f-9727-7b6244bcaa57.png)

**Comment by little-brother** [comment]
Are you import into a new table or into an existing?
![изображение](https://user-images.githubusercontent.com/20204037/146997695-7e5ee877-bdf6-4b15-9864-47269a41e0bc.png)

I tried import to existing and I've got the same DB4S error message (I already fixed this bug in development build).

> 1. by clicking "column names in first line" the importers was going to ignore this duplication.

DB4S shows the same error
![изображение](https://user-images.githubusercontent.com/20204037/146998885-9f52f8c6-06e9-4005-9687-96ae2bb5b79a.png)
I think how to process duplicate column should be customizable. Ignoring is a not obvious behaviour. 

> 2. BTW, If I delete all " (quotes) with Notepad++ Sqlite-gui is still unable to import the CSV

Please try [1.6.6-alpha.zip](https://github.com/little-brother/sqlite-gui/files/7758238/1.6.6-alpha.zip)
This version shows errors on failed import.

> 3. I was referring to cast empty "cells" as NULL.

It's already imported as `NULL`
![изображение](https://user-images.githubusercontent.com/20204037/146999443-7c39283d-c118-493b-921f-45de6e0324a3.png)
Any text value has light gray color. `NULL`s have own light blue color.
I added empty 3 rows, so you can see the 3-last NULLable blue rows.

**Comment by SilvioGrosso** [comment]
Hello @little-brother 

**I am testing 1.6.5**

1)
Now the error messages are correct (as regards the checks) while importing CSV files

2)
What does not still work are the CSV files with ""
e.g.:
"SFR_ID","DATE_CONSIGN,"MATRICE_COD"
1,"2020-01-10","RICE"

I suppose this bug is not fixed yet... :-)
I always import my CSV files into existing tables (which I create with SQL code, previously)

For instance, here is the error message where I am told there no such column (whereas DATA_CONSEGNA column is indeed available in the CSV file)

![immagine](https://user-images.githubusercontent.com/33007383/147002093-26baec8b-58e6-4238-978e-43e6d4a21583.png)

**Comment by little-brother** [comment]
> 2. "SFR_ID","DATE_CONSIGN,"MATRICE_COD"

Please check: there is a missing quote after `_CONSIGN`. I added it and import was done.

3. Could you open `ANFI_2020`-node and paste screenshot in a navigation tree?

**Comment by SilvioGrosso** [comment]
Hello @little-brother 

1)
With 1.6.6 alpha I can now import CSV files quoted with "". 
The bug was due to the extra space. You were right

2) Just out of curisosity, I have checked again both Db Browser and SqliteStudio
They are both able to import CSV files where "only" the name of 2 columns differ (as usual into existing tables in the database).

For instance the existing table has "DATA_CONSEGNA" column whereas the CSV file imported has "DATA_CONSEGNA**TA**" column instead (as name).
In your screenshot it looks like Db Browser fails to do so...
On my systems (Windows 10 - latest version of Db Browser) it succeeds

See this video:

https://user-images.githubusercontent.com/33007383/147005536-46d1ffb0-0926-4b93-a37d-9917e1a92ef4.mp4

**Comment by little-brother** [comment]
DB4S always trims column names and also removes spaces from it. That is why `DATA CONSEGNA ` will be inserted into `DATACONSEGNA`.

**Comment by SilvioGrosso** [comment]
Hello,

> DB4S always removes spaces from columns names

I didn't know about that.
What it is odd is that my table has the column as DATA_CONSEGNA (underscore) without spaces
In my SQL code for creating tables I never add spaces for the names of the columes (I put always underscores)
The CSV file, which I have just imported, has DATA_CONSEGNA**TA**. Again without spaces.

Unless the underscore is treated as space by DB4S ?

See this screenshot:
![immagine](https://user-images.githubusercontent.com/33007383/147008087-3c981de4-badb-4c14-b8da-4b232620782e.png)

**Comment by little-brother** [comment]
> In my SQL code for creating tables I never add spaces for the names of the columes (I put always underscores)
It's a common practice because with underscore you don't need to quote names.

> Unless the underscore is treated as space by DB4S 

Nope. Only spaces and perhaps TABs. I'll add some option in Import CSV dialog to provide similar DB4S features.

**Comment by little-brother** [comment]
Some options are added.
