### ISSUE TITLE
In memory database?

### ISSUE THREAD

**Issue by jungle-boogie** [little-brother/sqlite-gui#9]
Hello,

How can I create an in memory database using `sqlite-gui`? If no database is open, I cannot execute a query.

Thanks!

**Comment by little-brother** [comment]
At this moment you should open any database to execute an query (you can input any name in Open dialog).
I'll add this ability in the next release (coming soon).

Thanks for the feature lack report!

**Comment by jungle-boogie** [comment]
FYI, a new version of SQLite was released.

https://www.sqlite.org/releaselog/3_35_5.html

**Comment by little-brother** [comment]
**jungle-boogie**, thanks :) There was an another work to do.
Since 1.5.0: hold Shift and click "Open" to open the in-memory database.
