### ISSUE TITLE
Check constraints not implemented in the GUI (1.6.6 alpha)

### ISSUE THREAD

**Issue by SilvioGrosso** [little-brother/sqlite-gui#90]
Hello @little-brother 

I have noticed a little bug
Windows 10 (64 bit)
Sqlite-gui 1.6.6 alpha (the version you prepared to fix a previous bug of mine...)

Paste this SQL code:
create table names 
(id check (typeof(id) = 'integer'),
name check (typeof(name) = 'text'))

If you insert some rows through SQL code everything works as expected (all checks are respected):
Insert into names values (1, 'Mark');

On the contrary when you try to insert some row with the GUIs (add row) the check are not working.

See this video with all my steps:

https://user-images.githubusercontent.com/33007383/147545951-5e4a836f-4f22-4c28-aa1b-9c918e62bd3b.mp4

**Comment by little-brother** [comment]
Thanks. Yes, it's a bug.

**Comment by little-brother** [comment]
Fixed.
