### ISSUE TITLE
Refresh Tree not totally implemented (v. 1.6.6 alpha) for tables

### ISSUE THREAD

**Issue by SilvioGrosso** [little-brother/sqlite-gui#91]
Hello @little-brother 

sqlite-gui 1.6.6 alpha.
Windows 10 (64 bit)

I have noticed a little incosistency and I suppose it is expected but I ask just to make sure It is indeed a missing feature :-)

When I create and drop a table, through some SQL, code the "tree" with all the tables is not always refreshed automatically.
Sometimes it is refreshed automatically and others I am forced to click on it (Tables) and choose "Refresh"

I have noticed it is refreshed when you start working with the GUIs but as soon as you create other new tables (and drop them), later on, you are forced to refresh the tree manually to visualize them.

With Db Browser the refresh, when creating - dropping tables, is always **automatically done** in the GUIs. You are not forced to refresh the GUIs. 
On the contrary with SqliteStudio you are forced to refresh the tree to visualize the tables (when you create - drop them).
Therefore sqlite-gui is 50%, as behaviour, as regards the 2 previous softwares :-)

See this video with all my steps (to create drop tables)
**Btw; notice also at 0:30 this videeo,** where I write some code in the GUIs (drop...) : there is always a **| blinking** when I type the text. This occurs only with Sqlite-gui: no others softwares on my computer show this | | | "cursor" when I type some text):

https://user-images.githubusercontent.com/33007383/147547091-54ebf34e-73b6-4805-943a-7320cba59a70.mp4

**Comment by little-brother** [comment]
Hmm. The sqlite-gui has to update the tree when an query contains `drop table`/`create table` or like that.
Perhaps | | | adds some unprinted chars and therefore `drop table` isn't really `drop table`. 
I thought that I solved the | | | problem (issue #25) but Windows10 has own opinion :( I'll check how to fix it.

**Comment by SilvioGrosso** [comment]
Hello @little-brother ,

> I thought that I solved the | | | problem (issue #25) but Windows10 has own opinion :( I'll check how to fix it.

Strangely enough, Windows 8.1 (x64) everything works fine.
The | is always in front of the text (in essence it is not "delayed" behind, when you type very fast something)
I have checked on a different notebook, ASUS computer, where I run Windows 8.1 (CPU I7, with 8 gb RAM).

**Comment by little-brother** [comment]
It looks like the [editor component](https://docs.microsoft.com/en-us/windows/win32/controls/rich-edit-controls) x64 in Win10 is also broken. I though it was only x32 issue (that is why x32 version contains `msftedit.dll` from Win7). Perhaps I should add `msftedit.dll`-x64 to distributive too.

> Could you paste drop table workers from an another editor and execute it?

It should localize the problem. If the tree is refreshed on pasted `drop table workers`, it will be mean that x64-control adds non-visible chars when printing | | |.

**Comment by SilvioGrosso** [comment]
Hello @little-brother 



 > Could you paste drop table workers from an another editor and execute it?

I am not sure I understand correctly what you mean...
But, I have just pasted from Notepad++ the Sql code (DROP TABLE users;) into sqlite-gui and I have executed (F9) the code. The tree was not refreshed automatically (to delete  the table users). I had to click on "Refresh" manually.

**Comment by SilvioGrosso** [comment]
The same lack of refresh occurs when you rename a table (e.g alter table t1 rename to t2).

The name of the table is refreshed only when you open sqlite-gui for the first time (and you write some SQL code); later on, you have to refresh the tree manually (click "Refresh" on tables) when you write some SQL code. 
As usual, If you close the application and reopen it the refresh is done automaticall (but later it stops...).

Windows 10 (x64)
Sqlite-gui 1.6.6 alpha

**Comment by little-brother** [comment]
> I am not sure I understand correctly what you mean...

Thanks. You understood correctly.

>  later on, you have to refresh the tree manually (click "Refresh" on tables)

Ok, I'll check code to fix it.

**Comment by little-brother** [comment]
Perhaps, this issue is replated with #92 : the table list is updated when only zero rows were changed and DDL-statement was found. But the changed count is returned incorrectly.

**Comment by SilvioGrosso** [comment]
I have always worked with Db Browser (Windows 10) and everything is refreshed properly, automatically. Every version I have tested over the past years has this option implemented.

Previously, I was working with SqliteStudio where you have to manually refresh the tree (which is quite tedious...).
I suppose SqliteStudio has not implemented this feature.

With Sqlite-gui is half-baked in that it only works as soon as you start a new session :-)

**Comment by little-brother** [comment]
Fixed.
