### ISSUE TITLE
Blinking of SQL lines when selecting data

### ISSUE THREAD

**Issue by SilvioGrosso** [little-brother/sqlite-gui#93]
Hello @little-brother 

Another strange behaviour on Windows 10 (x64)
Sqlite-gui 1.6.6 alpha

When you select a long SQL code (many lines) there is a lot of blinking on the GUIs.
No other softwares on my computer show this strange effect (tested many of them: e.g. Notepad++ etc)
To tell you the truth it is quite fun to see all SQL  letters "dancing" in the GUIs like crazy :-)

**EDIT:**
This strange bug **also occurs on Windows 8.1 (x64)** with Sqlite-gui 1.6.5 (stable version).
Just tested on a different notebook computer.

I have recorded this video:

https://user-images.githubusercontent.com/33007383/147595816-07572750-3c2e-4a1b-bbf5-958312eb5a13.mp4

**Comment by little-brother** [comment]
Do you have the same bahaviour for x32 version?

**Comment by SilvioGrosso** [comment]
Yep. It blinks the same.
Windows 10 (x64)

I have just tested the ZIP: sqlite-gui.1.6.5

**Comment by little-brother** [comment]
Thanks. I repeated this bug under Win10.

**Comment by little-brother** [comment]
Fixed.
