### ISSUE TITLE
New SQLite - 3.37.1

### ISSUE THREAD

**Issue by jungle-boogie** [little-brother/sqlite-gui#94]
Hi,

SQLite 3.37.1 released today!
https://sqlite.org/releaselog/3_37_1.html

Looks like you have a few bugs opened, so no rush on a release - just letting you know.

Thanks!

**Comment by little-brother** [comment]
> no rush on a release

There is no rush in any case. Currently I'm working on another my project. So at least 2-3 weeks no release is planned (also I should fix all opened issue + implement one-two features).

**Comment by jungle-boogie** [comment]
Looking forward to it!

**Comment by little-brother** [comment]
Updated.
