### ISSUE TITLE
Ctrl + z: undo more than one character at a time

### ISSUE THREAD

**Issue by jungle-boogie** [little-brother/sqlite-gui#97]
Hello,

Thanks for your new release of `sqlite-gui`! I am very thankful to have you continue to maintain this application. 
One thing I've noticed for awhile is that `ctrl+z` only works on one character at a time.

Could it be improved to operate on more than one character?

Reported in
```
SQLite database editor
GUI version: 1.6.6
Architecture: x86-64
SQLite version: 3.37.2
Encryption support: Yes
Build date: Feb 10 2022
```

**Comment by little-brother** [comment]
Is it look correct? 

https://user-images.githubusercontent.com/20204037/153649970-4ff0676b-2c03-43c7-b7be-fe9e4c1f4418.mp4

Perhaps x64-version Win10 requires `msftedit.dll` too. Please check x32-version. Do it has the same problem?

**Comment by little-brother** [comment]
I tested the app on Win10x64 and I've got the same result. Do you need something else?
There is an issue with rollback an whole  word relating to editor component. I don't know how to control it.

**Comment by jungle-boogie** [comment]
Yes, that's what I see. Although if you have spaces in between your words, it undoes just one character at a time.

**Comment by little-brother** [comment]
Hmm, I checked SQLiteStudio and DB4S. 
Studio deleted deletes one-by-one chars, 
DB4S has an unpredictable behaviour and deletes all non-autocomplete text. 

Could you provide more details about what wrong with current sqlite-gui deletion? I thought that only last char is deleted e.g.
```
abc
// Ctrl + Z
ab
// Ctrl + Z
abc
```
But under Win7/Win10 is not true. And therefore it's ok.

**Comment by jungle-boogie** [comment]
Thanks for the review. I can live with how the undo works in `sqlite-gui`.
