### ISSUE TITLE
Open Pdf file with external editor (feature request)

### ISSUE THREAD

**Issue by SilvioGrosso** [little-brother/sqlite-gui#98]
Hello @little-brother 

Here is a feature request.
Thanks a lot for considering it in case it might be added in the future
sqlite-gui is indeed an amazing software :smile:

With Db Browser and other open source editors (e.g. Dbeaver) it is possible to open with an external editor some  PDFs file stored as blob in a sqlite database.
I would like to propose a simila option for sqlite-gui. More precisaly, for Windows and Linux.

To be more precise:
create table images
(id integer not null primary key,
name text,
image blob);

insert into images values
(1, 'image1', readfile("D:\prova.pdf"))

Now I would like to open this PDF file with an external software: on Windows usually this is Acrobat reader.

Here is a screenshot with Db browser with this exact feature available (the PDF file is opened with Acrobat reader):

![dbbrowser_pdf png](https://user-images.githubusercontent.com/33007383/154772910-f0c3793a-bec5-4f4d-bb40-81c60ea7f3d4.jpg)

Here is a video where I show the steps to create a table with a PDF file (sqltie-gui) and how I open this pdf with dbeaver (Windows 10):

https://user-images.githubusercontent.com/33007383/154773011-b0e541b9-c2e9-446b-9113-e5c79f2b65f4.mp4

**Comment by jungle-boogie** [comment]
If pdf support is added, where would it end?

There’s also pictures, audio, video, etc that could be stored at a blob.

Does Browser 4 SQLite open all those files?

IMO, this may not be the best path forward for a lightweight gui app.

By the way, I assumed SQLite-gui works on windows only. Does it work on
Linux as well?

**Comment by SilvioGrosso** [comment]
Hello @jungle-boogie 

> By the way, I assumed SQLite-gui works on windows only. 

In all truth, I don't know.
Most open source GUIs (dbeaver, db  browser, sqlitestudio) for sqlite which I work with has got a Linux version as well (on top of Windows...) :smile:
Since most open source developers work on Linux I have assumed this is the case for little-brother as well :smile:
Once in a while I work on Linux (KDE desktop  - Kubuntu) but at work I usually stay on Windows 10

>If pdf support is added, where would it end?
>There’s also pictures, audio, video, etc that could be stored at a blob.

This is very a technical question and it depends entirely on little-brother roadmap :smile:
In addition, in my experience, it is generally not suggested to store the whole blob in a database because with many files stored (images, pdf etc) it quickly slows down the performances.
My use-case is to store "small" files: 200-300 kb each. Usually my database might store 100 files at most (as blob). Total size of the final database would be around 20-30 Mb.
In all truth, I have never stored any video (mp4 etc) or RAW (nef etc) images inside my databases and I suppose it is unlikely I would do so (for performances issues..) in the future.

Allowing to **visualize** PDFs as blob is implemented with many open source GUIs I work with (e.g. Dbeaver, Db browser). On Windows 10, they simply launch a different softwares (.exe).
With many commercial softwares it is implemented as well. For instance take sqlmaestro:
https://www.sqlmaestro.com/products/sqlite/maestro/help/06_05_00_blob_viewer/

With Db browser, you can "only" launch an external application (e.g. Acrobat reader) to visualize your PDFs (stored internally in the database as blobs.  On the contrary, with images (png, jpeg) the support is very good. For instance, with a select query you can visualize a preview of your image in the query results. See this screenshot:
![immagine](https://user-images.githubusercontent.com/33007383/154793632-ab83675d-3ab9-464d-99e6-5ff70a0751a8.png)

**Comment by little-brother** [comment]
1. Perhaps sqlite-gui can be run on Linux via [Wine](https://en.wikipedia.org/wiki/Wine_(software)) or similar software. I don't have Linux machine to check it. The app can't be run natively on Linux because it uses a platform depended code (Windows API) unlike SqliteStudio/DB4S. They use [QT-library](https://en.wikipedia.org/wiki/Wine_(software)) for cross-platform development. This library allows to have one code for Linux/Windows/etc, but it requires an addidional  ~20mb disk size.
2. > open with an external editor some PDFs file stored as blob
    > If pdf support is added, where would it end?
   
    Yes, it possible and it won't take a lot of code for any extensions. pdf, images and some other files have a [standard file header](https://en.wikipedia.org/wiki/List_of_file_signatures). So the app should read first bytes of a blob, spot the appropriate extension, store the blob as `<somename>.<ext>` to temporary folder and say to Windows to open this file.
    To show `pdf`, `dwg` (Autocad), `psd` (Photoshop), `docx`, `xls` or another files, that Windows doesn't support from a box, inside the application is required to use additional libraries that have signifigantly more size than sqlite-gui and a complicated development pipeline. That is why I avoid them.

**Comment by little-brother** [comment]
Done. Now you can open any BLOB-data in external application.
